# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'IPSettings.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_IPSetting(object):
    def setupUi(self, IPSetting):
        IPSetting.setObjectName("IPSetting")
        IPSetting.resize(1428, 884)
        self.frame = QtWidgets.QFrame(IPSetting)
        self.frame.setGeometry(QtCore.QRect(12, 11, 1519, 894))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.layoutWidget_5 = QtWidgets.QWidget(self.frame)
        self.layoutWidget_5.setGeometry(QtCore.QRect(1150, 600, 158, 25))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget_5)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.SA_BTN = QtWidgets.QPushButton(self.layoutWidget_5)
        self.SA_BTN.setObjectName("SA_BTN")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.SA_BTN)
        self.CNCL_BTN = QtWidgets.QPushButton(self.layoutWidget_5)
        self.CNCL_BTN.setObjectName("CNCL_BTN")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.CNCL_BTN)
        self.layoutWidget = QtWidgets.QWidget(self.frame)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 1141, 631))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_5.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_4 = QtWidgets.QGroupBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.CSC_IP_LB = QtWidgets.QLabel(self.groupBox_4)
        self.CSC_IP_LB.setGeometry(QtCore.QRect(11, 21, 59, 16))
        self.CSC_IP_LB.setObjectName("CSC_IP_LB")
        self.CSC_P_LB = QtWidgets.QLabel(self.groupBox_4)
        self.CSC_P_LB.setGeometry(QtCore.QRect(11, 53, 48, 16))
        self.CSC_P_LB.setObjectName("CSC_P_LB")
        self.CSC_D_LB = QtWidgets.QLabel(self.groupBox_4)
        self.CSC_D_LB.setGeometry(QtCore.QRect(11, 115, 26, 16))
        self.CSC_D_LB.setObjectName("CSC_D_LB")
        self.CSC_SW_LE = QtWidgets.QTextEdit(self.groupBox_4)
        self.CSC_SW_LE.setGeometry(QtCore.QRect(76, 84, 194, 25))
        self.CSC_SW_LE.setObjectName("CSC_SW_LE")
        self.CSC_IP_LE = QtWidgets.QTextEdit(self.groupBox_4)
        self.CSC_IP_LE.setGeometry(QtCore.QRect(76, 21, 194, 26))
        self.CSC_IP_LE.setObjectName("CSC_IP_LE")
        self.CSC_P_LE = QtWidgets.QTextEdit(self.groupBox_4)
        self.CSC_P_LE.setGeometry(QtCore.QRect(76, 53, 194, 25))
        self.CSC_P_LE.setObjectName("CSC_P_LE")
        self.CSC_D_LE = QtWidgets.QTextEdit(self.groupBox_4)
        self.CSC_D_LE.setGeometry(QtCore.QRect(76, 115, 61, 25))
        self.CSC_D_LE.setObjectName("CSC_D_LE")
        self.CSC_SW_LB = QtWidgets.QLabel(self.groupBox_4)
        self.CSC_SW_LB.setGeometry(QtCore.QRect(11, 84, 51, 16))
        self.CSC_SW_LB.setObjectName("CSC_SW_LB")
        self.CSC_Y_LE = QtWidgets.QTextEdit(self.groupBox_4)
        self.CSC_Y_LE.setGeometry(QtCore.QRect(209, 115, 61, 25))
        self.CSC_Y_LE.setObjectName("CSC_Y_LE")
        self.CSC_M_LE = QtWidgets.QTextEdit(self.groupBox_4)
        self.CSC_M_LE.setGeometry(QtCore.QRect(143, 115, 60, 25))
        self.CSC_M_LE.setObjectName("CSC_M_LE")
        self.frame_3 = QtWidgets.QFrame(self.groupBox_4)
        self.frame_3.setGeometry(QtCore.QRect(0, 0, 281, 151))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.frame_3.raise_()
        self.CSC_IP_LB.raise_()
        self.CSC_P_LB.raise_()
        self.CSC_D_LB.raise_()
        self.CSC_SW_LE.raise_()
        self.CSC_IP_LE.raise_()
        self.CSC_P_LE.raise_()
        self.CSC_D_LE.raise_()
        self.CSC_SW_LB.raise_()
        self.CSC_Y_LE.raise_()
        self.CSC_M_LE.raise_()
        self.gridLayout.addWidget(self.groupBox_4, 0, 0, 1, 1)
        self.groupBox_7 = QtWidgets.QGroupBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.groupBox_7.setFont(font)
        self.groupBox_7.setObjectName("groupBox_7")
        self.frame_4 = QtWidgets.QFrame(self.groupBox_7)
        self.frame_4.setGeometry(QtCore.QRect(0, 0, 281, 151))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.CSVG_D_LB = QtWidgets.QLabel(self.groupBox_7)
        self.CSVG_D_LB.setGeometry(QtCore.QRect(11, 115, 26, 16))
        self.CSVG_D_LB.setObjectName("CSVG_D_LB")
        self.CSVG_V_LE = QtWidgets.QTextEdit(self.groupBox_7)
        self.CSVG_V_LE.setGeometry(QtCore.QRect(76, 84, 194, 25))
        self.CSVG_V_LE.setObjectName("CSVG_V_LE")
        self.CSVG_IP_LE = QtWidgets.QTextEdit(self.groupBox_7)
        self.CSVG_IP_LE.setGeometry(QtCore.QRect(76, 21, 194, 26))
        self.CSVG_IP_LE.setObjectName("CSVG_IP_LE")
        self.CSVG_IP_LB = QtWidgets.QLabel(self.groupBox_7)
        self.CSVG_IP_LB.setGeometry(QtCore.QRect(11, 21, 59, 16))
        self.CSVG_IP_LB.setObjectName("CSVG_IP_LB")
        self.CSVG_P_LE = QtWidgets.QTextEdit(self.groupBox_7)
        self.CSVG_P_LE.setGeometry(QtCore.QRect(76, 53, 194, 25))
        self.CSVG_P_LE.setObjectName("CSVG_P_LE")
        self.CSVG_P_LB = QtWidgets.QLabel(self.groupBox_7)
        self.CSVG_P_LB.setGeometry(QtCore.QRect(11, 53, 48, 16))
        self.CSVG_P_LB.setObjectName("CSVG_P_LB")
        self.CSVG_V_LB = QtWidgets.QLabel(self.groupBox_7)
        self.CSVG_V_LB.setGeometry(QtCore.QRect(11, 84, 51, 16))
        self.CSVG_V_LB.setObjectName("CSVG_V_LB")
        self.CSVG_D_LE = QtWidgets.QTextEdit(self.groupBox_7)
        self.CSVG_D_LE.setGeometry(QtCore.QRect(76, 115, 61, 25))
        self.CSVG_D_LE.setObjectName("CSVG_D_LE")
        self.CSVG_Y_LE = QtWidgets.QTextEdit(self.groupBox_7)
        self.CSVG_Y_LE.setGeometry(QtCore.QRect(209, 115, 61, 25))
        self.CSVG_Y_LE.setObjectName("CSVG_Y_LE")
        self.CSVG_M_LE = QtWidgets.QTextEdit(self.groupBox_7)
        self.CSVG_M_LE.setGeometry(QtCore.QRect(143, 115, 60, 25))
        self.CSVG_M_LE.setObjectName("CSVG_M_LE")
        self.gridLayout.addWidget(self.groupBox_7, 0, 1, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.frame_5 = QtWidgets.QFrame(self.groupBox_3)
        self.frame_5.setGeometry(QtCore.QRect(0, 0, 281, 151))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.CSIE1_D_LB = QtWidgets.QLabel(self.groupBox_3)
        self.CSIE1_D_LB.setGeometry(QtCore.QRect(11, 115, 26, 16))
        self.CSIE1_D_LB.setObjectName("CSIE1_D_LB")
        self.CSIE1_V_LE = QtWidgets.QTextEdit(self.groupBox_3)
        self.CSIE1_V_LE.setGeometry(QtCore.QRect(76, 84, 194, 25))
        self.CSIE1_V_LE.setObjectName("CSIE1_V_LE")
        self.CSIE1_IP_LE = QtWidgets.QTextEdit(self.groupBox_3)
        self.CSIE1_IP_LE.setGeometry(QtCore.QRect(76, 21, 194, 26))
        self.CSIE1_IP_LE.setObjectName("CSIE1_IP_LE")
        self.CSIE1_IP_LB = QtWidgets.QLabel(self.groupBox_3)
        self.CSIE1_IP_LB.setGeometry(QtCore.QRect(11, 21, 59, 16))
        self.CSIE1_IP_LB.setObjectName("CSIE1_IP_LB")
        self.CSIE1_P_LE = QtWidgets.QTextEdit(self.groupBox_3)
        self.CSIE1_P_LE.setGeometry(QtCore.QRect(76, 53, 194, 25))
        self.CSIE1_P_LE.setObjectName("CSIE1_P_LE")
        self.CSIE1_P_LB = QtWidgets.QLabel(self.groupBox_3)
        self.CSIE1_P_LB.setGeometry(QtCore.QRect(11, 53, 48, 16))
        self.CSIE1_P_LB.setObjectName("CSIE1_P_LB")
        self.CSIE1_D_LE = QtWidgets.QTextEdit(self.groupBox_3)
        self.CSIE1_D_LE.setGeometry(QtCore.QRect(76, 115, 61, 25))
        self.CSIE1_D_LE.setObjectName("CSIE1_D_LE")
        self.CSIE1_V_LB = QtWidgets.QLabel(self.groupBox_3)
        self.CSIE1_V_LB.setGeometry(QtCore.QRect(11, 84, 51, 16))
        self.CSIE1_V_LB.setObjectName("CSIE1_V_LB")
        self.CSIE1_Y_LE = QtWidgets.QTextEdit(self.groupBox_3)
        self.CSIE1_Y_LE.setGeometry(QtCore.QRect(209, 115, 61, 25))
        self.CSIE1_Y_LE.setObjectName("CSIE1_Y_LE")
        self.CSIE1_M_LE = QtWidgets.QTextEdit(self.groupBox_3)
        self.CSIE1_M_LE.setGeometry(QtCore.QRect(143, 115, 60, 25))
        self.CSIE1_M_LE.setObjectName("CSIE1_M_LE")
        self.gridLayout.addWidget(self.groupBox_3, 0, 2, 1, 1)
        self.groupBox_6 = QtWidgets.QGroupBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.groupBox_6.setFont(font)
        self.groupBox_6.setObjectName("groupBox_6")
        self.frame_6 = QtWidgets.QFrame(self.groupBox_6)
        self.frame_6.setGeometry(QtCore.QRect(0, 0, 281, 151))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.DVLS_IP_LE = QtWidgets.QTextEdit(self.groupBox_6)
        self.DVLS_IP_LE.setGeometry(QtCore.QRect(76, 21, 194, 26))
        self.DVLS_IP_LE.setObjectName("DVLS_IP_LE")
        self.DVLS_P_LB = QtWidgets.QLabel(self.groupBox_6)
        self.DVLS_P_LB.setGeometry(QtCore.QRect(11, 53, 48, 16))
        self.DVLS_P_LB.setObjectName("DVLS_P_LB")
        self.DVLS_D_LE = QtWidgets.QTextEdit(self.groupBox_6)
        self.DVLS_D_LE.setGeometry(QtCore.QRect(76, 115, 61, 25))
        self.DVLS_D_LE.setObjectName("DVLS_D_LE")
        self.DVLS_P_LE = QtWidgets.QTextEdit(self.groupBox_6)
        self.DVLS_P_LE.setGeometry(QtCore.QRect(76, 53, 194, 25))
        self.DVLS_P_LE.setObjectName("DVLS_P_LE")
        self.DVLS_Y_LE = QtWidgets.QTextEdit(self.groupBox_6)
        self.DVLS_Y_LE.setGeometry(QtCore.QRect(209, 115, 61, 25))
        self.DVLS_Y_LE.setObjectName("DVLS_Y_LE")
        self.DVLS_V_LB = QtWidgets.QLabel(self.groupBox_6)
        self.DVLS_V_LB.setGeometry(QtCore.QRect(11, 84, 51, 16))
        self.DVLS_V_LB.setObjectName("DVLS_V_LB")
        self.DVLS_M_LE = QtWidgets.QTextEdit(self.groupBox_6)
        self.DVLS_M_LE.setGeometry(QtCore.QRect(143, 115, 60, 25))
        self.DVLS_M_LE.setObjectName("DVLS_M_LE")
        self.DVLS_V_LE = QtWidgets.QTextEdit(self.groupBox_6)
        self.DVLS_V_LE.setGeometry(QtCore.QRect(76, 84, 194, 25))
        self.DVLS_V_LE.setObjectName("DVLS_V_LE")
        self.DVLS_D_LB = QtWidgets.QLabel(self.groupBox_6)
        self.DVLS_D_LB.setGeometry(QtCore.QRect(11, 115, 26, 16))
        self.DVLS_D_LB.setObjectName("DVLS_D_LB")
        self.DVLS_IP_LB = QtWidgets.QLabel(self.groupBox_6)
        self.DVLS_IP_LB.setGeometry(QtCore.QRect(11, 21, 59, 16))
        self.DVLS_IP_LB.setObjectName("DVLS_IP_LB")
        self.gridLayout.addWidget(self.groupBox_6, 0, 3, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox_9 = QtWidgets.QGroupBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.groupBox_9.setFont(font)
        self.groupBox_9.setObjectName("groupBox_9")
        self.frame_7 = QtWidgets.QFrame(self.groupBox_9)
        self.frame_7.setGeometry(QtCore.QRect(0, 0, 281, 151))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.CSLS1_Y_LE = QtWidgets.QTextEdit(self.groupBox_9)
        self.CSLS1_Y_LE.setGeometry(QtCore.QRect(209, 115, 61, 25))
        self.CSLS1_Y_LE.setObjectName("CSLS1_Y_LE")
        self.CSLS1_M_LE = QtWidgets.QTextEdit(self.groupBox_9)
        self.CSLS1_M_LE.setGeometry(QtCore.QRect(143, 115, 60, 25))
        self.CSLS1_M_LE.setObjectName("CSLS1_M_LE")
        self.CSLS1_D_LB = QtWidgets.QLabel(self.groupBox_9)
        self.CSLS1_D_LB.setGeometry(QtCore.QRect(11, 115, 26, 16))
        self.CSLS1_D_LB.setObjectName("CSLS1_D_LB")
        self.CSLS1_V_LE = QtWidgets.QTextEdit(self.groupBox_9)
        self.CSLS1_V_LE.setGeometry(QtCore.QRect(76, 84, 194, 25))
        self.CSLS1_V_LE.setObjectName("CSLS1_V_LE")
        self.CSLS1_IP_LB = QtWidgets.QLabel(self.groupBox_9)
        self.CSLS1_IP_LB.setGeometry(QtCore.QRect(11, 21, 59, 16))
        self.CSLS1_IP_LB.setObjectName("CSLS1_IP_LB")
        self.CSLS1_P_LB = QtWidgets.QLabel(self.groupBox_9)
        self.CSLS1_P_LB.setGeometry(QtCore.QRect(11, 53, 48, 16))
        self.CSLS1_P_LB.setObjectName("CSLS1_P_LB")
        self.CSLS1_IP_LE = QtWidgets.QTextEdit(self.groupBox_9)
        self.CSLS1_IP_LE.setGeometry(QtCore.QRect(76, 21, 194, 26))
        self.CSLS1_IP_LE.setObjectName("CSLS1_IP_LE")
        self.CSLS1_D_LE = QtWidgets.QTextEdit(self.groupBox_9)
        self.CSLS1_D_LE.setGeometry(QtCore.QRect(76, 115, 61, 25))
        self.CSLS1_D_LE.setObjectName("CSLS1_D_LE")
        self.CSLS1_V_LB = QtWidgets.QLabel(self.groupBox_9)
        self.CSLS1_V_LB.setGeometry(QtCore.QRect(11, 84, 51, 16))
        self.CSLS1_V_LB.setObjectName("CSLS1_V_LB")
        self.CSLS1_P_LE = QtWidgets.QTextEdit(self.groupBox_9)
        self.CSLS1_P_LE.setGeometry(QtCore.QRect(76, 53, 194, 25))
        self.CSLS1_P_LE.setObjectName("CSLS1_P_LE")
        self.gridLayout_2.addWidget(self.groupBox_9, 0, 0, 1, 1)
        self.groupBox_10 = QtWidgets.QGroupBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.groupBox_10.setFont(font)
        self.groupBox_10.setObjectName("groupBox_10")
        self.frame_8 = QtWidgets.QFrame(self.groupBox_10)
        self.frame_8.setGeometry(QtCore.QRect(0, 0, 281, 151))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.CSIL_D_LE = QtWidgets.QTextEdit(self.groupBox_10)
        self.CSIL_D_LE.setGeometry(QtCore.QRect(76, 115, 61, 25))
        self.CSIL_D_LE.setObjectName("CSIL_D_LE")
        self.CSIL_Y_LE = QtWidgets.QTextEdit(self.groupBox_10)
        self.CSIL_Y_LE.setGeometry(QtCore.QRect(209, 115, 61, 25))
        self.CSIL_Y_LE.setObjectName("CSIL_Y_LE")
        self.CSIL_M_LE = QtWidgets.QTextEdit(self.groupBox_10)
        self.CSIL_M_LE.setGeometry(QtCore.QRect(143, 115, 60, 25))
        self.CSIL_M_LE.setObjectName("CSIL_M_LE")
        self.CSIL_IP_LE = QtWidgets.QTextEdit(self.groupBox_10)
        self.CSIL_IP_LE.setGeometry(QtCore.QRect(76, 21, 194, 26))
        self.CSIL_IP_LE.setObjectName("CSIL_IP_LE")
        self.CSIL_D_LB = QtWidgets.QLabel(self.groupBox_10)
        self.CSIL_D_LB.setGeometry(QtCore.QRect(11, 115, 26, 16))
        self.CSIL_D_LB.setObjectName("CSIL_D_LB")
        self.CSIL_V_LE = QtWidgets.QTextEdit(self.groupBox_10)
        self.CSIL_V_LE.setGeometry(QtCore.QRect(76, 84, 194, 25))
        self.CSIL_V_LE.setObjectName("CSIL_V_LE")
        self.CSIL_IP_LB = QtWidgets.QLabel(self.groupBox_10)
        self.CSIL_IP_LB.setGeometry(QtCore.QRect(11, 21, 59, 16))
        self.CSIL_IP_LB.setObjectName("CSIL_IP_LB")
        self.CSIL_P_LE = QtWidgets.QTextEdit(self.groupBox_10)
        self.CSIL_P_LE.setGeometry(QtCore.QRect(76, 53, 194, 25))
        self.CSIL_P_LE.setObjectName("CSIL_P_LE")
        self.CSIL_V_LB = QtWidgets.QLabel(self.groupBox_10)
        self.CSIL_V_LB.setGeometry(QtCore.QRect(11, 84, 51, 16))
        self.CSIL_V_LB.setObjectName("CSIL_V_LB")
        self.CSIL_P_LB = QtWidgets.QLabel(self.groupBox_10)
        self.CSIL_P_LB.setGeometry(QtCore.QRect(11, 53, 48, 16))
        self.CSIL_P_LB.setObjectName("CSIL_P_LB")
        self.gridLayout_2.addWidget(self.groupBox_10, 0, 1, 1, 1)
        self.groupBox_11 = QtWidgets.QGroupBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.groupBox_11.setFont(font)
        self.groupBox_11.setObjectName("groupBox_11")
        self.frame_9 = QtWidgets.QFrame(self.groupBox_11)
        self.frame_9.setGeometry(QtCore.QRect(0, 0, 281, 151))
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.CSIE2_Y_LE = QtWidgets.QTextEdit(self.groupBox_11)
        self.CSIE2_Y_LE.setGeometry(QtCore.QRect(209, 115, 61, 25))
        self.CSIE2_Y_LE.setObjectName("CSIE2_Y_LE")
        self.CSIE2_M_LE = QtWidgets.QTextEdit(self.groupBox_11)
        self.CSIE2_M_LE.setGeometry(QtCore.QRect(143, 115, 60, 25))
        self.CSIE2_M_LE.setObjectName("CSIE2_M_LE")
        self.CSIE2_V_LE = QtWidgets.QTextEdit(self.groupBox_11)
        self.CSIE2_V_LE.setGeometry(QtCore.QRect(76, 84, 194, 25))
        self.CSIE2_V_LE.setObjectName("CSIE2_V_LE")
        self.CSIE2_D_LB = QtWidgets.QLabel(self.groupBox_11)
        self.CSIE2_D_LB.setGeometry(QtCore.QRect(11, 115, 26, 16))
        self.CSIE2_D_LB.setObjectName("CSIE2_D_LB")
        self.CSIE2_IP_LE = QtWidgets.QTextEdit(self.groupBox_11)
        self.CSIE2_IP_LE.setGeometry(QtCore.QRect(76, 21, 194, 26))
        self.CSIE2_IP_LE.setObjectName("CSIE2_IP_LE")
        self.CSIE2_P_LB = QtWidgets.QLabel(self.groupBox_11)
        self.CSIE2_P_LB.setGeometry(QtCore.QRect(11, 53, 48, 16))
        self.CSIE2_P_LB.setObjectName("CSIE2_P_LB")
        self.CSIE2_IP_LB = QtWidgets.QLabel(self.groupBox_11)
        self.CSIE2_IP_LB.setGeometry(QtCore.QRect(11, 21, 59, 16))
        self.CSIE2_IP_LB.setObjectName("CSIE2_IP_LB")
        self.CSIE2_P_LE = QtWidgets.QTextEdit(self.groupBox_11)
        self.CSIE2_P_LE.setGeometry(QtCore.QRect(76, 53, 194, 25))
        self.CSIE2_P_LE.setObjectName("CSIE2_P_LE")
        self.CSIE2_V_LB = QtWidgets.QLabel(self.groupBox_11)
        self.CSIE2_V_LB.setGeometry(QtCore.QRect(11, 84, 51, 16))
        self.CSIE2_V_LB.setObjectName("CSIE2_V_LB")
        self.CSIE2_D_LE = QtWidgets.QTextEdit(self.groupBox_11)
        self.CSIE2_D_LE.setGeometry(QtCore.QRect(76, 115, 61, 25))
        self.CSIE2_D_LE.setObjectName("CSIE2_D_LE")
        self.gridLayout_2.addWidget(self.groupBox_11, 0, 2, 1, 1)
        self.groupBox_12 = QtWidgets.QGroupBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.groupBox_12.setFont(font)
        self.groupBox_12.setObjectName("groupBox_12")
        self.frame_10 = QtWidgets.QFrame(self.groupBox_12)
        self.frame_10.setGeometry(QtCore.QRect(0, 0, 281, 151))
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.DVVDR_D_LE_2 = QtWidgets.QLabel(self.groupBox_12)
        self.DVVDR_D_LE_2.setGeometry(QtCore.QRect(11, 115, 26, 16))
        self.DVVDR_D_LE_2.setObjectName("DVVDR_D_LE_2")
        self.DVVDR_V_LE = QtWidgets.QTextEdit(self.groupBox_12)
        self.DVVDR_V_LE.setGeometry(QtCore.QRect(76, 84, 194, 25))
        self.DVVDR_V_LE.setObjectName("DVVDR_V_LE")
        self.DVVDR_IP_LE = QtWidgets.QTextEdit(self.groupBox_12)
        self.DVVDR_IP_LE.setGeometry(QtCore.QRect(76, 21, 194, 26))
        self.DVVDR_IP_LE.setObjectName("DVVDR_IP_LE")
        self.DVVDR_IP_LE_2 = QtWidgets.QLabel(self.groupBox_12)
        self.DVVDR_IP_LE_2.setGeometry(QtCore.QRect(11, 21, 59, 16))
        self.DVVDR_IP_LE_2.setObjectName("DVVDR_IP_LE_2")
        self.DVVDR_P_LE = QtWidgets.QTextEdit(self.groupBox_12)
        self.DVVDR_P_LE.setGeometry(QtCore.QRect(76, 53, 194, 25))
        self.DVVDR_P_LE.setObjectName("DVVDR_P_LE")
        self.DVVDR_P_LE_2 = QtWidgets.QLabel(self.groupBox_12)
        self.DVVDR_P_LE_2.setGeometry(QtCore.QRect(11, 53, 48, 16))
        self.DVVDR_P_LE_2.setObjectName("DVVDR_P_LE_2")
        self.DVVDR_V_LE_2 = QtWidgets.QLabel(self.groupBox_12)
        self.DVVDR_V_LE_2.setGeometry(QtCore.QRect(11, 84, 51, 16))
        self.DVVDR_V_LE_2.setObjectName("DVVDR_V_LE_2")
        self.DVVDR_D_LE = QtWidgets.QTextEdit(self.groupBox_12)
        self.DVVDR_D_LE.setGeometry(QtCore.QRect(76, 115, 61, 25))
        self.DVVDR_D_LE.setObjectName("DVVDR_D_LE")
        self.DVVDR_Y_LE = QtWidgets.QTextEdit(self.groupBox_12)
        self.DVVDR_Y_LE.setGeometry(QtCore.QRect(209, 115, 61, 25))
        self.DVVDR_Y_LE.setObjectName("DVVDR_Y_LE")
        self.DVVDR_M_LE = QtWidgets.QTextEdit(self.groupBox_12)
        self.DVVDR_M_LE.setGeometry(QtCore.QRect(143, 115, 60, 25))
        self.DVVDR_M_LE.setObjectName("DVVDR_M_LE")
        self.gridLayout_2.addWidget(self.groupBox_12, 0, 3, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_2, 1, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox_16 = QtWidgets.QGroupBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.groupBox_16.setFont(font)
        self.groupBox_16.setObjectName("groupBox_16")
        self.frame_14 = QtWidgets.QFrame(self.groupBox_16)
        self.frame_14.setGeometry(QtCore.QRect(0, 0, 281, 151))
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.DVVP_D_LB = QtWidgets.QLabel(self.groupBox_16)
        self.DVVP_D_LB.setGeometry(QtCore.QRect(11, 115, 26, 16))
        self.DVVP_D_LB.setObjectName("DVVP_D_LB")
        self.DVVP_V_LE = QtWidgets.QTextEdit(self.groupBox_16)
        self.DVVP_V_LE.setGeometry(QtCore.QRect(76, 84, 194, 25))
        self.DVVP_V_LE.setObjectName("DVVP_V_LE")
        self.DVVP_IP_LE = QtWidgets.QTextEdit(self.groupBox_16)
        self.DVVP_IP_LE.setGeometry(QtCore.QRect(76, 21, 194, 26))
        self.DVVP_IP_LE.setObjectName("DVVP_IP_LE")
        self.DVVP_IP_LB = QtWidgets.QLabel(self.groupBox_16)
        self.DVVP_IP_LB.setGeometry(QtCore.QRect(11, 21, 59, 16))
        self.DVVP_IP_LB.setObjectName("DVVP_IP_LB")
        self.DVVP_P_LE = QtWidgets.QTextEdit(self.groupBox_16)
        self.DVVP_P_LE.setGeometry(QtCore.QRect(76, 53, 194, 25))
        self.DVVP_P_LE.setObjectName("DVVP_P_LE")
        self.DVVP_P_LB = QtWidgets.QLabel(self.groupBox_16)
        self.DVVP_P_LB.setGeometry(QtCore.QRect(11, 53, 48, 16))
        self.DVVP_P_LB.setObjectName("DVVP_P_LB")
        self.DVVP_V_LB = QtWidgets.QLabel(self.groupBox_16)
        self.DVVP_V_LB.setGeometry(QtCore.QRect(11, 84, 51, 16))
        self.DVVP_V_LB.setObjectName("DVVP_V_LB")
        self.DVVP_D_LE = QtWidgets.QTextEdit(self.groupBox_16)
        self.DVVP_D_LE.setGeometry(QtCore.QRect(76, 115, 61, 25))
        self.DVVP_D_LE.setObjectName("DVVP_D_LE")
        self.DVVP_Y_LE = QtWidgets.QTextEdit(self.groupBox_16)
        self.DVVP_Y_LE.setGeometry(QtCore.QRect(209, 115, 61, 25))
        self.DVVP_Y_LE.setObjectName("DVVP_Y_LE")
        self.DVVP_M_LE = QtWidgets.QTextEdit(self.groupBox_16)
        self.DVVP_M_LE.setGeometry(QtCore.QRect(143, 115, 60, 25))
        self.DVVP_M_LE.setObjectName("DVVP_M_LE")
        self.gridLayout_3.addWidget(self.groupBox_16, 0, 3, 1, 1)
        self.groupBox_15 = QtWidgets.QGroupBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.groupBox_15.setFont(font)
        self.groupBox_15.setObjectName("groupBox_15")
        self.frame_13 = QtWidgets.QFrame(self.groupBox_15)
        self.frame_13.setGeometry(QtCore.QRect(0, 0, 281, 151))
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.CSLR_V_LE = QtWidgets.QTextEdit(self.groupBox_15)
        self.CSLR_V_LE.setGeometry(QtCore.QRect(76, 84, 194, 25))
        self.CSLR_V_LE.setObjectName("CSLR_V_LE")
        self.label_81 = QtWidgets.QLabel(self.groupBox_15)
        self.label_81.setGeometry(QtCore.QRect(11, 115, 26, 16))
        self.label_81.setObjectName("label_81")
        self.CSLR_IP_LE = QtWidgets.QTextEdit(self.groupBox_15)
        self.CSLR_IP_LE.setGeometry(QtCore.QRect(76, 21, 194, 26))
        self.CSLR_IP_LE.setObjectName("CSLR_IP_LE")
        self.label_83 = QtWidgets.QLabel(self.groupBox_15)
        self.label_83.setGeometry(QtCore.QRect(11, 53, 48, 16))
        self.label_83.setObjectName("label_83")
        self.label_82 = QtWidgets.QLabel(self.groupBox_15)
        self.label_82.setGeometry(QtCore.QRect(11, 21, 59, 16))
        self.label_82.setObjectName("label_82")
        self.CSLR_P_LE = QtWidgets.QTextEdit(self.groupBox_15)
        self.CSLR_P_LE.setGeometry(QtCore.QRect(76, 53, 194, 25))
        self.CSLR_P_LE.setObjectName("CSLR_P_LE")
        self.CSLR_D_LE = QtWidgets.QTextEdit(self.groupBox_15)
        self.CSLR_D_LE.setGeometry(QtCore.QRect(76, 115, 61, 25))
        self.CSLR_D_LE.setObjectName("CSLR_D_LE")
        self.label_84 = QtWidgets.QLabel(self.groupBox_15)
        self.label_84.setGeometry(QtCore.QRect(11, 84, 51, 16))
        self.label_84.setObjectName("label_84")
        self.CSLR_Y_LE = QtWidgets.QTextEdit(self.groupBox_15)
        self.CSLR_Y_LE.setGeometry(QtCore.QRect(209, 115, 61, 25))
        self.CSLR_Y_LE.setObjectName("CSLR_Y_LE")
        self.CSLR_M_LE = QtWidgets.QTextEdit(self.groupBox_15)
        self.CSLR_M_LE.setGeometry(QtCore.QRect(143, 115, 60, 25))
        self.CSLR_M_LE.setObjectName("CSLR_M_LE")
        self.gridLayout_3.addWidget(self.groupBox_15, 0, 2, 1, 1)
        self.groupBox_13 = QtWidgets.QGroupBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.groupBox_13.setFont(font)
        self.groupBox_13.setObjectName("groupBox_13")
        self.frame_11 = QtWidgets.QFrame(self.groupBox_13)
        self.frame_11.setGeometry(QtCore.QRect(0, 0, 281, 151))
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.CSLS2_V_LE = QtWidgets.QTextEdit(self.groupBox_13)
        self.CSLS2_V_LE.setGeometry(QtCore.QRect(76, 84, 194, 25))
        self.CSLS2_V_LE.setObjectName("CSLS2_V_LE")
        self.CSLS2_IP_LE = QtWidgets.QTextEdit(self.groupBox_13)
        self.CSLS2_IP_LE.setGeometry(QtCore.QRect(76, 21, 194, 26))
        self.CSLS2_IP_LE.setObjectName("CSLS2_IP_LE")
        self.CSLS2_D_LB = QtWidgets.QLabel(self.groupBox_13)
        self.CSLS2_D_LB.setGeometry(QtCore.QRect(11, 115, 26, 16))
        self.CSLS2_D_LB.setObjectName("CSLS2_D_LB")
        self.CSLS2_IP_LB = QtWidgets.QLabel(self.groupBox_13)
        self.CSLS2_IP_LB.setGeometry(QtCore.QRect(11, 21, 59, 16))
        self.CSLS2_IP_LB.setObjectName("CSLS2_IP_LB")
        self.CSLS2_P_LE = QtWidgets.QTextEdit(self.groupBox_13)
        self.CSLS2_P_LE.setGeometry(QtCore.QRect(76, 53, 194, 25))
        self.CSLS2_P_LE.setObjectName("CSLS2_P_LE")
        self.CSLS2_P_LB = QtWidgets.QLabel(self.groupBox_13)
        self.CSLS2_P_LB.setGeometry(QtCore.QRect(11, 53, 48, 16))
        self.CSLS2_P_LB.setObjectName("CSLS2_P_LB")
        self.CSLS2_V_LB = QtWidgets.QLabel(self.groupBox_13)
        self.CSLS2_V_LB.setGeometry(QtCore.QRect(11, 84, 51, 16))
        self.CSLS2_V_LB.setObjectName("CSLS2_V_LB")
        self.CSLS2_Y_LE = QtWidgets.QTextEdit(self.groupBox_13)
        self.CSLS2_Y_LE.setGeometry(QtCore.QRect(209, 115, 61, 25))
        self.CSLS2_Y_LE.setObjectName("CSLS2_Y_LE")
        self.CSLS2_D_LE = QtWidgets.QTextEdit(self.groupBox_13)
        self.CSLS2_D_LE.setGeometry(QtCore.QRect(76, 115, 61, 25))
        self.CSLS2_D_LE.setObjectName("CSLS2_D_LE")
        self.CSLS2_M_LE = QtWidgets.QTextEdit(self.groupBox_13)
        self.CSLS2_M_LE.setGeometry(QtCore.QRect(143, 115, 60, 25))
        self.CSLS2_M_LE.setObjectName("CSLS2_M_LE")
        self.gridLayout_3.addWidget(self.groupBox_13, 0, 0, 1, 1)
        self.groupBox_14 = QtWidgets.QGroupBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.groupBox_14.setFont(font)
        self.groupBox_14.setObjectName("groupBox_14")
        self.frame_12 = QtWidgets.QFrame(self.groupBox_14)
        self.frame_12.setGeometry(QtCore.QRect(0, 0, 281, 151))
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.CSTID_V_LB_2 = QtWidgets.QLabel(self.groupBox_14)
        self.CSTID_V_LB_2.setGeometry(QtCore.QRect(11, 115, 26, 16))
        self.CSTID_V_LB_2.setObjectName("CSTID_V_LB_2")
        self.CSTID_V_LE = QtWidgets.QTextEdit(self.groupBox_14)
        self.CSTID_V_LE.setGeometry(QtCore.QRect(76, 84, 194, 25))
        self.CSTID_V_LE.setObjectName("CSTID_V_LE")
        self.CSTID_IP_LE = QtWidgets.QTextEdit(self.groupBox_14)
        self.CSTID_IP_LE.setGeometry(QtCore.QRect(76, 21, 194, 26))
        self.CSTID_IP_LE.setObjectName("CSTID_IP_LE")
        self.CSTID_P_LE = QtWidgets.QTextEdit(self.groupBox_14)
        self.CSTID_P_LE.setGeometry(QtCore.QRect(76, 53, 194, 25))
        self.CSTID_P_LE.setObjectName("CSTID_P_LE")
        self.CSTID_IP_LB = QtWidgets.QLabel(self.groupBox_14)
        self.CSTID_IP_LB.setGeometry(QtCore.QRect(11, 21, 59, 16))
        self.CSTID_IP_LB.setObjectName("CSTID_IP_LB")
        self.CSTID_V_LB = QtWidgets.QLabel(self.groupBox_14)
        self.CSTID_V_LB.setGeometry(QtCore.QRect(11, 84, 51, 16))
        self.CSTID_V_LB.setObjectName("CSTID_V_LB")
        self.CSTID_D_LE = QtWidgets.QTextEdit(self.groupBox_14)
        self.CSTID_D_LE.setGeometry(QtCore.QRect(76, 115, 61, 25))
        self.CSTID_D_LE.setObjectName("CSTID_D_LE")
        self.CSTID_Y_LE = QtWidgets.QTextEdit(self.groupBox_14)
        self.CSTID_Y_LE.setGeometry(QtCore.QRect(209, 115, 61, 25))
        self.CSTID_Y_LE.setObjectName("CSTID_Y_LE")
        self.CSTID_M_LE = QtWidgets.QTextEdit(self.groupBox_14)
        self.CSTID_M_LE.setGeometry(QtCore.QRect(143, 115, 60, 25))
        self.CSTID_M_LE.setObjectName("CSTID_M_LE")
        self.CSTID_P_LB = QtWidgets.QLabel(self.groupBox_14)
        self.CSTID_P_LB.setGeometry(QtCore.QRect(11, 53, 48, 16))
        self.CSTID_P_LB.setObjectName("CSTID_P_LB")
        self.gridLayout_3.addWidget(self.groupBox_14, 0, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_3, 2, 0, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.groupBox_18 = QtWidgets.QGroupBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.groupBox_18.setFont(font)
        self.groupBox_18.setObjectName("groupBox_18")
        self.frame_16 = QtWidgets.QFrame(self.groupBox_18)
        self.frame_16.setGeometry(QtCore.QRect(0, 0, 281, 151))
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.CSVP_V_LE = QtWidgets.QTextEdit(self.groupBox_18)
        self.CSVP_V_LE.setGeometry(QtCore.QRect(76, 84, 194, 25))
        self.CSVP_V_LE.setObjectName("CSVP_V_LE")
        self.CSVP_D_LB = QtWidgets.QLabel(self.groupBox_18)
        self.CSVP_D_LB.setGeometry(QtCore.QRect(11, 115, 26, 16))
        self.CSVP_D_LB.setObjectName("CSVP_D_LB")
        self.CSVP_IP_LE = QtWidgets.QTextEdit(self.groupBox_18)
        self.CSVP_IP_LE.setGeometry(QtCore.QRect(76, 21, 194, 26))
        self.CSVP_IP_LE.setObjectName("CSVP_IP_LE")
        self.CSVP_P_LB = QtWidgets.QLabel(self.groupBox_18)
        self.CSVP_P_LB.setGeometry(QtCore.QRect(11, 53, 48, 16))
        self.CSVP_P_LB.setObjectName("CSVP_P_LB")
        self.CSVP_IP_LB = QtWidgets.QLabel(self.groupBox_18)
        self.CSVP_IP_LB.setGeometry(QtCore.QRect(11, 21, 59, 16))
        self.CSVP_IP_LB.setObjectName("CSVP_IP_LB")
        self.CSVP_P_LE = QtWidgets.QTextEdit(self.groupBox_18)
        self.CSVP_P_LE.setGeometry(QtCore.QRect(76, 53, 194, 25))
        self.CSVP_P_LE.setObjectName("CSVP_P_LE")
        self.CSVP_D_LE = QtWidgets.QTextEdit(self.groupBox_18)
        self.CSVP_D_LE.setGeometry(QtCore.QRect(76, 115, 61, 25))
        self.CSVP_D_LE.setObjectName("CSVP_D_LE")
        self.CSVP_V_LB = QtWidgets.QLabel(self.groupBox_18)
        self.CSVP_V_LB.setGeometry(QtCore.QRect(11, 84, 51, 16))
        self.CSVP_V_LB.setObjectName("CSVP_V_LB")
        self.CSVP_Y_LE = QtWidgets.QTextEdit(self.groupBox_18)
        self.CSVP_Y_LE.setGeometry(QtCore.QRect(209, 115, 61, 25))
        self.CSVP_Y_LE.setObjectName("CSVP_Y_LE")
        self.CSVP_M_LE = QtWidgets.QTextEdit(self.groupBox_18)
        self.CSVP_M_LE.setGeometry(QtCore.QRect(143, 115, 60, 25))
        self.CSVP_M_LE.setObjectName("CSVP_M_LE")
        self.gridLayout_4.addWidget(self.groupBox_18, 0, 1, 1, 1)
        self.groupBox_19 = QtWidgets.QGroupBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.groupBox_19.setFont(font)
        self.groupBox_19.setObjectName("groupBox_19")
        self.frame_17 = QtWidgets.QFrame(self.groupBox_19)
        self.frame_17.setGeometry(QtCore.QRect(0, 0, 281, 151))
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.DVC_V_LE = QtWidgets.QTextEdit(self.groupBox_19)
        self.DVC_V_LE.setGeometry(QtCore.QRect(76, 84, 194, 25))
        self.DVC_V_LE.setObjectName("DVC_V_LE")
        self.label_97 = QtWidgets.QLabel(self.groupBox_19)
        self.label_97.setGeometry(QtCore.QRect(11, 115, 26, 16))
        self.label_97.setObjectName("label_97")
        self.DVC_IP_LE = QtWidgets.QTextEdit(self.groupBox_19)
        self.DVC_IP_LE.setGeometry(QtCore.QRect(76, 21, 194, 26))
        self.DVC_IP_LE.setObjectName("DVC_IP_LE")
        self.label_98 = QtWidgets.QLabel(self.groupBox_19)
        self.label_98.setGeometry(QtCore.QRect(11, 21, 59, 16))
        self.label_98.setObjectName("label_98")
        self.DVC_P_LE = QtWidgets.QTextEdit(self.groupBox_19)
        self.DVC_P_LE.setGeometry(QtCore.QRect(76, 53, 194, 25))
        self.DVC_P_LE.setObjectName("DVC_P_LE")
        self.label_99 = QtWidgets.QLabel(self.groupBox_19)
        self.label_99.setGeometry(QtCore.QRect(11, 53, 48, 16))
        self.label_99.setObjectName("label_99")
        self.DVC_D_LE = QtWidgets.QTextEdit(self.groupBox_19)
        self.DVC_D_LE.setGeometry(QtCore.QRect(76, 115, 61, 25))
        self.DVC_D_LE.setObjectName("DVC_D_LE")
        self.label_100 = QtWidgets.QLabel(self.groupBox_19)
        self.label_100.setGeometry(QtCore.QRect(11, 84, 51, 16))
        self.label_100.setObjectName("label_100")
        self.DVC_Y_LE = QtWidgets.QTextEdit(self.groupBox_19)
        self.DVC_Y_LE.setGeometry(QtCore.QRect(209, 115, 61, 25))
        self.DVC_Y_LE.setObjectName("DVC_Y_LE")
        self.DVC_M_LE = QtWidgets.QTextEdit(self.groupBox_19)
        self.DVC_M_LE.setGeometry(QtCore.QRect(143, 115, 60, 25))
        self.DVC_M_LE.setObjectName("DVC_M_LE")
        self.gridLayout_4.addWidget(self.groupBox_19, 0, 2, 1, 1)
        self.groupBox_20 = QtWidgets.QGroupBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.groupBox_20.setFont(font)
        self.groupBox_20.setObjectName("groupBox_20")
        self.frame_18 = QtWidgets.QFrame(self.groupBox_20)
        self.frame_18.setGeometry(QtCore.QRect(0, 0, 281, 151))
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.DVLR_V_LE = QtWidgets.QTextEdit(self.groupBox_20)
        self.DVLR_V_LE.setGeometry(QtCore.QRect(76, 83, 194, 25))
        self.DVLR_V_LE.setObjectName("DVLR_V_LE")
        self.DVLR_IP_LE = QtWidgets.QTextEdit(self.groupBox_20)
        self.DVLR_IP_LE.setGeometry(QtCore.QRect(76, 20, 194, 26))
        self.DVLR_IP_LE.setObjectName("DVLR_IP_LE")
        self.DVLR_D_LB = QtWidgets.QLabel(self.groupBox_20)
        self.DVLR_D_LB.setGeometry(QtCore.QRect(11, 114, 26, 16))
        self.DVLR_D_LB.setObjectName("DVLR_D_LB")
        self.DVLR_P_LE = QtWidgets.QTextEdit(self.groupBox_20)
        self.DVLR_P_LE.setGeometry(QtCore.QRect(76, 52, 194, 25))
        self.DVLR_P_LE.setObjectName("DVLR_P_LE")
        self.DVLR_IP_LB = QtWidgets.QLabel(self.groupBox_20)
        self.DVLR_IP_LB.setGeometry(QtCore.QRect(11, 20, 59, 16))
        self.DVLR_IP_LB.setObjectName("DVLR_IP_LB")
        self.DVLR_P_LB = QtWidgets.QLabel(self.groupBox_20)
        self.DVLR_P_LB.setGeometry(QtCore.QRect(11, 52, 48, 16))
        self.DVLR_P_LB.setObjectName("DVLR_P_LB")
        self.DVLR_D_LE = QtWidgets.QTextEdit(self.groupBox_20)
        self.DVLR_D_LE.setGeometry(QtCore.QRect(76, 114, 61, 25))
        self.DVLR_D_LE.setObjectName("DVLR_D_LE")
        self.DVLR_V_LB = QtWidgets.QLabel(self.groupBox_20)
        self.DVLR_V_LB.setGeometry(QtCore.QRect(11, 83, 51, 16))
        self.DVLR_V_LB.setObjectName("DVLR_V_LB")
        self.DVLR_Y_LE = QtWidgets.QTextEdit(self.groupBox_20)
        self.DVLR_Y_LE.setGeometry(QtCore.QRect(209, 114, 61, 25))
        self.DVLR_Y_LE.setObjectName("DVLR_Y_LE")
        self.DVLR_M_LE = QtWidgets.QTextEdit(self.groupBox_20)
        self.DVLR_M_LE.setGeometry(QtCore.QRect(143, 114, 60, 25))
        self.DVLR_M_LE.setObjectName("DVLR_M_LE")
        self.gridLayout_4.addWidget(self.groupBox_20, 0, 3, 1, 1)
        self.groupBox_17 = QtWidgets.QGroupBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.groupBox_17.setFont(font)
        self.groupBox_17.setObjectName("groupBox_17")
        self.frame_15 = QtWidgets.QFrame(self.groupBox_17)
        self.frame_15.setGeometry(QtCore.QRect(0, 0, 281, 151))
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.CSVD_IP_LE = QtWidgets.QTextEdit(self.groupBox_17)
        self.CSVD_IP_LE.setGeometry(QtCore.QRect(76, 21, 194, 26))
        self.CSVD_IP_LE.setObjectName("CSVD_IP_LE")
        self.CSVD_P_LB = QtWidgets.QLabel(self.groupBox_17)
        self.CSVD_P_LB.setGeometry(QtCore.QRect(11, 53, 48, 16))
        self.CSVD_P_LB.setObjectName("CSVD_P_LB")
        self.CSVD_IP_LB = QtWidgets.QLabel(self.groupBox_17)
        self.CSVD_IP_LB.setGeometry(QtCore.QRect(11, 21, 59, 16))
        self.CSVD_IP_LB.setObjectName("CSVD_IP_LB")
        self.CSVD_P_LE = QtWidgets.QTextEdit(self.groupBox_17)
        self.CSVD_P_LE.setGeometry(QtCore.QRect(76, 53, 194, 25))
        self.CSVD_P_LE.setObjectName("CSVD_P_LE")
        self.CSVD_V_LB = QtWidgets.QLabel(self.groupBox_17)
        self.CSVD_V_LB.setGeometry(QtCore.QRect(11, 84, 51, 16))
        self.CSVD_V_LB.setObjectName("CSVD_V_LB")
        self.CSVD_D_LE = QtWidgets.QTextEdit(self.groupBox_17)
        self.CSVD_D_LE.setGeometry(QtCore.QRect(76, 115, 61, 25))
        self.CSVD_D_LE.setObjectName("CSVD_D_LE")
        self.CSVD_Y_LE = QtWidgets.QTextEdit(self.groupBox_17)
        self.CSVD_Y_LE.setGeometry(QtCore.QRect(209, 115, 61, 25))
        self.CSVD_Y_LE.setObjectName("CSVD_Y_LE")
        self.CSVD_M_LE = QtWidgets.QTextEdit(self.groupBox_17)
        self.CSVD_M_LE.setGeometry(QtCore.QRect(143, 115, 60, 25))
        self.CSVD_M_LE.setObjectName("CSVD_M_LE")
        self.CSVD_D_LB = QtWidgets.QLabel(self.groupBox_17)
        self.CSVD_D_LB.setGeometry(QtCore.QRect(11, 115, 26, 16))
        self.CSVD_D_LB.setObjectName("CSVD_D_LB")
        self.CSVD_V_LE = QtWidgets.QTextEdit(self.groupBox_17)
        self.CSVD_V_LE.setGeometry(QtCore.QRect(76, 84, 194, 25))
        self.CSVD_V_LE.setObjectName("CSVD_V_LE")
        self.gridLayout_4.addWidget(self.groupBox_17, 0, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 3, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(IPSetting)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 1161, 641))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame_2.raise_()
        self.frame.raise_()

        self.retranslateUi(IPSetting)
        QtCore.QMetaObject.connectSlotsByName(IPSetting)

    def retranslateUi(self, IPSetting):
        _translate = QtCore.QCoreApplication.translate
        IPSetting.setWindowTitle(_translate("IPSetting", "Form"))
        self.SA_BTN.setText(_translate("IPSetting", "SAVE"))
        self.CNCL_BTN.setText(_translate("IPSetting", "CANCLE"))
        self.groupBox_4.setTitle(_translate("IPSetting", "CS COMPUTER"))
        self.CSC_IP_LB.setText(_translate("IPSetting", "IP ADDRESS"))
        self.CSC_P_LB.setText(_translate("IPSetting", "PORT NO."))
        self.CSC_D_LB.setText(_translate("IPSetting", "DATE"))
        self.CSC_SW_LB.setText(_translate("IPSetting", "SW V. NO."))
        self.groupBox_7.setTitle(_translate("IPSetting", "VOIP GATEWAY"))
        self.CSVG_D_LB.setText(_translate("IPSetting", "DATE"))
        self.CSVG_IP_LB.setText(_translate("IPSetting", "IP ADDRESS"))
        self.CSVG_P_LB.setText(_translate("IPSetting", "PORT NO."))
        self.CSVG_V_LB.setText(_translate("IPSetting", "SW V. NO."))
        self.groupBox_3.setTitle(_translate("IPSetting", "IP ENCRYPTOR 1"))
        self.CSIE1_D_LB.setText(_translate("IPSetting", "DATE"))
        self.CSIE1_IP_LB.setText(_translate("IPSetting", "IP ADDRESS"))
        self.CSIE1_P_LB.setText(_translate("IPSetting", "PORT NO."))
        self.CSIE1_V_LB.setText(_translate("IPSetting", "SW V. NO."))
        self.groupBox_6.setTitle(_translate("IPSetting", "DV LAN SW"))
        self.DVLS_P_LB.setText(_translate("IPSetting", "PORT NO."))
        self.DVLS_V_LB.setText(_translate("IPSetting", "SW V. NO."))
        self.DVLS_D_LB.setText(_translate("IPSetting", "DATE"))
        self.DVLS_IP_LB.setText(_translate("IPSetting", "IP ADDRESS"))
        self.groupBox_9.setTitle(_translate("IPSetting", "CS LAN SW 1"))
        self.CSLS1_D_LB.setText(_translate("IPSetting", "DATE"))
        self.CSLS1_IP_LB.setText(_translate("IPSetting", "IP ADDRESS"))
        self.CSLS1_P_LB.setText(_translate("IPSetting", "PORT NO."))
        self.CSLS1_V_LB.setText(_translate("IPSetting", "SW V. NO."))
        self.groupBox_10.setTitle(_translate("IPSetting", "MINI IP LOGGER"))
        self.CSIL_D_LB.setText(_translate("IPSetting", "DATE"))
        self.CSIL_IP_LB.setText(_translate("IPSetting", "IP ADDRESS"))
        self.CSIL_V_LB.setText(_translate("IPSetting", "SW V. NO."))
        self.CSIL_P_LB.setText(_translate("IPSetting", "PORT NO."))
        self.groupBox_11.setTitle(_translate("IPSetting", "IP ENCRYPTION 2"))
        self.CSIE2_D_LB.setText(_translate("IPSetting", "DATE"))
        self.CSIE2_P_LB.setText(_translate("IPSetting", "PORT NO."))
        self.CSIE2_IP_LB.setText(_translate("IPSetting", "IP ADDRESS"))
        self.CSIE2_V_LB.setText(_translate("IPSetting", "SW V. NO."))
        self.groupBox_12.setTitle(_translate("IPSetting", "DV ENCODER RECODER"))
        self.DVVDR_D_LE_2.setText(_translate("IPSetting", "DATE"))
        self.DVVDR_IP_LE_2.setText(_translate("IPSetting", "IP ADDRESS"))
        self.DVVDR_P_LE_2.setText(_translate("IPSetting", "PORT NO."))
        self.DVVDR_V_LE_2.setText(_translate("IPSetting", "SW V. NO."))
        self.groupBox_16.setTitle(_translate("IPSetting", "DV VOIP PHONE"))
        self.DVVP_D_LB.setText(_translate("IPSetting", "DATE"))
        self.DVVP_IP_LB.setText(_translate("IPSetting", "IP ADDRESS"))
        self.DVVP_P_LB.setText(_translate("IPSetting", "PORT NO."))
        self.DVVP_V_LB.setText(_translate("IPSetting", "SW V. NO."))
        self.groupBox_15.setTitle(_translate("IPSetting", "CS LOS RADIO"))
        self.label_81.setText(_translate("IPSetting", "DATE"))
        self.label_83.setText(_translate("IPSetting", "PORT NO."))
        self.label_82.setText(_translate("IPSetting", "IP ADDRESS"))
        self.label_84.setText(_translate("IPSetting", "SW V. NO."))
        self.groupBox_13.setTitle(_translate("IPSetting", "CS LAN SW 2"))
        self.CSLS2_D_LB.setText(_translate("IPSetting", "DATE"))
        self.CSLS2_IP_LB.setText(_translate("IPSetting", "IP ADDRESS"))
        self.CSLS2_P_LB.setText(_translate("IPSetting", "PORT NO."))
        self.CSLS2_V_LB.setText(_translate("IPSetting", "SW V. NO."))
        self.groupBox_14.setTitle(_translate("IPSetting", "TID"))
        self.CSTID_V_LB_2.setText(_translate("IPSetting", "DATE"))
        self.CSTID_IP_LB.setText(_translate("IPSetting", "IP ADDRESS"))
        self.CSTID_V_LB.setText(_translate("IPSetting", "SW V. NO."))
        self.CSTID_P_LB.setText(_translate("IPSetting", "PORT NO."))
        self.groupBox_18.setTitle(_translate("IPSetting", "VOIP PHONE"))
        self.CSVP_D_LB.setText(_translate("IPSetting", "DATE"))
        self.CSVP_P_LB.setText(_translate("IPSetting", "PORT NO."))
        self.CSVP_IP_LB.setText(_translate("IPSetting", "IP ADDRESS"))
        self.CSVP_V_LB.setText(_translate("IPSetting", "SW V. NO."))
        self.groupBox_19.setTitle(_translate("IPSetting", "DV COMPUTER"))
        self.label_97.setText(_translate("IPSetting", "DATE"))
        self.label_98.setText(_translate("IPSetting", "IP ADDRESS"))
        self.label_99.setText(_translate("IPSetting", "PORT NO."))
        self.label_100.setText(_translate("IPSetting", "SW V. NO."))
        self.groupBox_20.setTitle(_translate("IPSetting", "DV LOS RADIO"))
        self.DVLR_D_LB.setText(_translate("IPSetting", "DATE"))
        self.DVLR_IP_LB.setText(_translate("IPSetting", "IP ADDRESS"))
        self.DVLR_P_LB.setText(_translate("IPSetting", "PORT NO."))
        self.DVLR_V_LB.setText(_translate("IPSetting", "SW V. NO."))
        self.groupBox_17.setTitle(_translate("IPSetting", "VIDEO ENCODER"))
        self.CSVD_P_LB.setText(_translate("IPSetting", "PORT NO."))
        self.CSVD_IP_LB.setText(_translate("IPSetting", "IP ADDRESS"))
        self.CSVD_V_LB.setText(_translate("IPSetting", "SW V. NO."))
        self.CSVD_D_LB.setText(_translate("IPSetting", "DATE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    IPSetting = QtWidgets.QWidget()
    ui = Ui_IPSetting()
    ui.setupUi(IPSetting)
    IPSetting.show()
    sys.exit(app.exec_())
