# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:\Python\CS_SIM_V1\App\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        self.OP_Mode = QtWidgets.QMenu(self.menubar)
        self.OP_Mode.setObjectName("OP_Mode")
        self.Maint_Mode = QtWidgets.QMenu(self.menubar)
        self.Maint_Mode.setObjectName("Maint_Mode")
        self.TR_Mode = QtWidgets.QMenu(self.menubar)
        self.TR_Mode.setObjectName("TR_Mode")
        self.Deployment = QtWidgets.QMenu(self.TR_Mode)
        self.Deployment.setObjectName("Deployment")
        self.Maint_Sim = QtWidgets.QMenu(self.TR_Mode)
        self.Maint_Sim.setObjectName("Maint_Sim")
        self.Settings = QtWidgets.QMenu(self.menubar)
        self.Settings.setObjectName("Settings")
        self.Help = QtWidgets.QMenu(self.menubar)
        self.Help.setObjectName("Help")
        self.About = QtWidgets.QMenu(self.menubar)
        self.About.setObjectName("About")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.Min_Win = QtWidgets.QAction(MainWindow)
        self.Min_Win.setObjectName("Min_Win")
        self.Max_Win = QtWidgets.QAction(MainWindow)
        self.Max_Win.setObjectName("Max_Win")
        self.Exit = QtWidgets.QAction(MainWindow)
        self.Exit.setObjectName("Exit")
        self.LRU_IP_Setting = QtWidgets.QAction(MainWindow)
        self.LRU_IP_Setting.setObjectName("LRU_IP_Setting")
        self.LRU_Status = QtWidgets.QAction(MainWindow)
        self.LRU_Status.setObjectName("LRU_Status")
        self.Mode_Selec = QtWidgets.QAction(MainWindow)
        self.Mode_Selec.setObjectName("Mode_Selec")
        self.VSAT_NMS_App = QtWidgets.QAction(MainWindow)
        self.VSAT_NMS_App.setObjectName("VSAT_NMS_App")
        self.VER_SW_App = QtWidgets.QAction(MainWindow)
        self.VER_SW_App.setObjectName("VER_SW_App")
        self.RF_Plng_Tool_App = QtWidgets.QAction(MainWindow)
        self.RF_Plng_Tool_App.setObjectName("RF_Plng_Tool_App")
        self.Fault_Sim = QtWidgets.QAction(MainWindow)
        self.Fault_Sim.setObjectName("Fault_Sim")
        self.Maint_Videos = QtWidgets.QAction(MainWindow)
        self.Maint_Videos.setObjectName("Maint_Videos")
        self.Maint_Files = QtWidgets.QAction(MainWindow)
        self.Maint_Files.setObjectName("Maint_Files")
        self.OP_Sim = QtWidgets.QAction(MainWindow)
        self.OP_Sim.setObjectName("OP_Sim")
        self.Dply_PPTs = QtWidgets.QAction(MainWindow)
        self.Dply_PPTs.setObjectName("Dply_PPTs")
        self.Dply_Manuals = QtWidgets.QAction(MainWindow)
        self.Dply_Manuals.setObjectName("Dply_Manuals")
        self.Dply_Videos = QtWidgets.QAction(MainWindow)
        self.Dply_Videos.setObjectName("Dply_Videos")
        self.Simr_with_Faults = QtWidgets.QAction(MainWindow)
        self.Simr_with_Faults.setObjectName("Simr_with_Faults")
        self.PPTs = QtWidgets.QAction(MainWindow)
        self.PPTs.setObjectName("PPTs")
        self.Manuals = QtWidgets.QAction(MainWindow)
        self.Manuals.setObjectName("Manuals")
        self.Tech_Manual = QtWidgets.QAction(MainWindow)
        self.Tech_Manual.setObjectName("Tech_Manual")
        self.Tech_Videos = QtWidgets.QAction(MainWindow)
        self.Tech_Videos.setObjectName("Tech_Videos")
        self.Pass_Reset = QtWidgets.QAction(MainWindow)
        self.Pass_Reset.setObjectName("Pass_Reset")
        self.menuMenu.addAction(self.Min_Win)
        self.menuMenu.addAction(self.Max_Win)
        self.menuMenu.addAction(self.Exit)
        self.OP_Mode.addAction(self.LRU_IP_Setting)
        self.OP_Mode.addAction(self.LRU_Status)
        self.OP_Mode.addAction(self.Mode_Selec)
        self.OP_Mode.addAction(self.VSAT_NMS_App)
        self.OP_Mode.addAction(self.VER_SW_App)
        self.OP_Mode.addAction(self.RF_Plng_Tool_App)
        self.Maint_Mode.addAction(self.Fault_Sim)
        self.Maint_Mode.addAction(self.Maint_Videos)
        self.Maint_Mode.addAction(self.Maint_Files)
        self.Deployment.addAction(self.Dply_PPTs)
        self.Deployment.addAction(self.Dply_Manuals)
        self.Deployment.addAction(self.Dply_Videos)
        self.Maint_Sim.addAction(self.Simr_with_Faults)
        self.Maint_Sim.addAction(self.PPTs)
        self.Maint_Sim.addAction(self.Manuals)
        self.Maint_Sim.addAction(self.Tech_Manual)
        self.Maint_Sim.addAction(self.Tech_Videos)
        self.TR_Mode.addAction(self.OP_Sim)
        self.TR_Mode.addAction(self.Maint_Sim.menuAction())
        self.TR_Mode.addAction(self.Deployment.menuAction())
        self.Settings.addAction(self.Pass_Reset)
        self.menubar.addAction(self.menuMenu.menuAction())
        self.menubar.addAction(self.OP_Mode.menuAction())
        self.menubar.addAction(self.Maint_Mode.menuAction())
        self.menubar.addAction(self.TR_Mode.menuAction())
        self.menubar.addAction(self.Settings.menuAction())
        self.menubar.addAction(self.Help.menuAction())
        self.menubar.addAction(self.About.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu"))
        self.OP_Mode.setTitle(_translate("MainWindow", "Operation Mode"))
        self.Maint_Mode.setTitle(_translate("MainWindow", "Maintenance Mode"))
        self.TR_Mode.setTitle(_translate("MainWindow", "Training Mode"))
        self.Deployment.setTitle(_translate("MainWindow", "Deployment"))
        self.Maint_Sim.setTitle(_translate("MainWindow", "Maintenance Simulator"))
        self.Settings.setTitle(_translate("MainWindow", "Settings"))
        self.Help.setTitle(_translate("MainWindow", "Help"))
        self.About.setTitle(_translate("MainWindow", "About"))
        self.Min_Win.setText(_translate("MainWindow", "Minimize"))
        self.Max_Win.setText(_translate("MainWindow", "Maxmaize"))
        self.Exit.setText(_translate("MainWindow", "Exit"))
        self.LRU_IP_Setting.setText(_translate("MainWindow", "LRU IP Setting"))
        self.LRU_Status.setText(_translate("MainWindow", "LRU Status"))
        self.Mode_Selec.setText(_translate("MainWindow", "Mode Selection"))
        self.VSAT_NMS_App.setText(_translate("MainWindow", "VSAT NMS APP"))
        self.VER_SW_App.setText(_translate("MainWindow", "VER S/W APP"))
        self.RF_Plng_Tool_App.setText(_translate("MainWindow", "RF Planning Tool APP"))
        self.Fault_Sim.setText(_translate("MainWindow", "Fault Simulation"))
        self.Maint_Videos.setText(_translate("MainWindow", "Maintenace Videos"))
        self.Maint_Files.setText(_translate("MainWindow", "Maintenance Files"))
        self.OP_Sim.setText(_translate("MainWindow", "Operation Simulation"))
        self.Dply_PPTs.setText(_translate("MainWindow", "PPTs"))
        self.Dply_Manuals.setText(_translate("MainWindow", "Manuals"))
        self.Dply_Videos.setText(_translate("MainWindow", "Videos"))
        self.Simr_with_Faults.setText(_translate("MainWindow", "Simulator with Faults"))
        self.PPTs.setText(_translate("MainWindow", "PPTs"))
        self.Manuals.setText(_translate("MainWindow", "Manuals"))
        self.Tech_Manual.setText(_translate("MainWindow", "Technical Manual"))
        self.Tech_Videos.setText(_translate("MainWindow", "Videos"))
        self.Pass_Reset.setText(_translate("MainWindow", "Password Reset"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
