# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OPWindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OPWindow(object):

    def setupUi(self, OPWindow):
        OPWindow.setObjectName("OPWindow")
        OPWindow.resize(1315, 716)
        OPWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(OPWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(40, 10, 1251, 921))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.scrollArea = QtWidgets.QScrollArea(self.tab)
        self.scrollArea.setGeometry(QtCore.QRect(-4, -16, 1251, 681))
        self.scrollArea.setStyleSheet("")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 1249, 679))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.frame_11 = QtWidgets.QFrame(self.scrollAreaWidgetContents_2)
        self.frame_11.setStyleSheet("")
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_11)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_18 = QtWidgets.QFrame(self.frame_11)
        self.frame_18.setMinimumSize(QtCore.QSize(380, 0))
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.gridLayout_37 = QtWidgets.QGridLayout(self.frame_18)
        self.gridLayout_37.setObjectName("gridLayout_37")
        self.CSC_gb_18 = QtWidgets.QGroupBox(self.frame_18)
        self.CSC_gb_18.setMinimumSize(QtCore.QSize(350, 0))
        font = QtGui.QFont()
        font.setItalic(False)
        font.setUnderline(False)
        self.CSC_gb_18.setFont(font)
        self.CSC_gb_18.setAutoFillBackground(False)
        self.CSC_gb_18.setStyleSheet("color: rgb(0, 0, 0);")
        self.CSC_gb_18.setFlat(False)
        self.CSC_gb_18.setCheckable(False)
        self.CSC_gb_18.setObjectName("CSC_gb_18")
        self.gridLayout_38 = QtWidgets.QGridLayout(self.CSC_gb_18)
        self.gridLayout_38.setObjectName("gridLayout_38")
        self.horizontalLayout_52 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_52.setObjectName("horizontalLayout_52")
        self.label_75 = QtWidgets.QLabel(self.CSC_gb_18)
        self.label_75.setObjectName("label_75")
        self.horizontalLayout_52.addWidget(self.label_75)
        self.CSTID_H_LE = QtWidgets.QLineEdit(self.CSC_gb_18)
        self.CSTID_H_LE.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.CSTID_H_LE.setObjectName("CSTID_H_LE")
        self.horizontalLayout_52.addWidget(self.CSTID_H_LE)
        spacerItem = QtWidgets.QSpacerItem(108, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_52.addItem(spacerItem)
        self.gridLayout_38.addLayout(self.horizontalLayout_52, 0, 0, 1, 1)
        self.gridLayout_37.addWidget(self.CSC_gb_18, 0, 0, 1, 1)
        self.horizontalLayout_4.addWidget(self.frame_18)
        self.frame_19 = QtWidgets.QFrame(self.frame_11)
        self.frame_19.setMinimumSize(QtCore.QSize(380, 0))
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_19)
        self.verticalLayout.setObjectName("verticalLayout")
        self.CSC_gb_19 = QtWidgets.QGroupBox(self.frame_19)
        self.CSC_gb_19.setMinimumSize(QtCore.QSize(350, 0))
        font = QtGui.QFont()
        font.setItalic(False)
        font.setUnderline(False)
        self.CSC_gb_19.setFont(font)
        self.CSC_gb_19.setAutoFillBackground(False)
        self.CSC_gb_19.setStyleSheet("color: rgb(0, 0, 0);")
        self.CSC_gb_19.setFlat(False)
        self.CSC_gb_19.setCheckable(False)
        self.CSC_gb_19.setObjectName("CSC_gb_19")
        self.gridLayout_40 = QtWidgets.QGridLayout(self.CSC_gb_19)
        self.gridLayout_40.setObjectName("gridLayout_40")
        self.horizontalLayout_54 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_54.setObjectName("horizontalLayout_54")
        self.label_78 = QtWidgets.QLabel(self.CSC_gb_19)
        self.label_78.setObjectName("label_78")
        self.horizontalLayout_54.addWidget(self.label_78)
        self.CSVP_H_LE = QtWidgets.QLineEdit(self.CSC_gb_19)
        self.CSVP_H_LE.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.CSVP_H_LE.setObjectName("CSVP_H_LE")
        self.horizontalLayout_54.addWidget(self.CSVP_H_LE)
        spacerItem1 = QtWidgets.QSpacerItem(108, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_54.addItem(spacerItem1)
        self.gridLayout_40.addLayout(self.horizontalLayout_54, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.CSC_gb_19)
        self.horizontalLayout_4.addWidget(self.frame_19)
        self.frame_25 = QtWidgets.QFrame(self.frame_11)
        self.frame_25.setMinimumSize(QtCore.QSize(380, 0))
        self.frame_25.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_25.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_25.setObjectName("frame_25")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_25)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.CSC_gb_25 = QtWidgets.QGroupBox(self.frame_25)
        self.CSC_gb_25.setMinimumSize(QtCore.QSize(350, 0))
        font = QtGui.QFont()
        font.setItalic(False)
        font.setUnderline(False)
        self.CSC_gb_25.setFont(font)
        self.CSC_gb_25.setAutoFillBackground(False)
        self.CSC_gb_25.setStyleSheet("color: rgb(0, 0, 0);")
        self.CSC_gb_25.setFlat(False)
        self.CSC_gb_25.setCheckable(False)
        self.CSC_gb_25.setObjectName("CSC_gb_25")
        self.gridLayout_52 = QtWidgets.QGridLayout(self.CSC_gb_25)
        self.gridLayout_52.setObjectName("gridLayout_52")
        self.horizontalLayout_65 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_65.setObjectName("horizontalLayout_65")
        self.label_100 = QtWidgets.QLabel(self.CSC_gb_25)
        self.label_100.setObjectName("label_100")
        self.horizontalLayout_65.addWidget(self.label_100)
        self.DVVP_H_LE = QtWidgets.QLineEdit(self.CSC_gb_25)
        self.DVVP_H_LE.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.DVVP_H_LE.setObjectName("DVVP_H_LE")
        self.horizontalLayout_65.addWidget(self.DVVP_H_LE)
        spacerItem2 = QtWidgets.QSpacerItem(108, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_65.addItem(spacerItem2)
        self.gridLayout_52.addLayout(self.horizontalLayout_65, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.CSC_gb_25)
        self.horizontalLayout_4.addWidget(self.frame_25)
        self.gridLayout.addLayout(self.horizontalLayout_4, 3, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_12 = QtWidgets.QFrame(self.frame_11)
        self.frame_12.setMinimumSize(QtCore.QSize(380, 0))
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_12)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.CSC_gb_12 = QtWidgets.QGroupBox(self.frame_12)
        self.CSC_gb_12.setMinimumSize(QtCore.QSize(350, 0))
        font = QtGui.QFont()
        font.setItalic(False)
        font.setUnderline(False)
        self.CSC_gb_12.setFont(font)
        self.CSC_gb_12.setAutoFillBackground(False)
        self.CSC_gb_12.setStyleSheet("border-color: rgb(255, 255, 255);\n"
"color: rgb(0, 0, 0);\n"
"border-width:3px\n"
"")
        self.CSC_gb_12.setFlat(False)
        self.CSC_gb_12.setCheckable(False)
        self.CSC_gb_12.setObjectName("CSC_gb_12")
        self.gridLayout_26 = QtWidgets.QGridLayout(self.CSC_gb_12)
        self.gridLayout_26.setObjectName("gridLayout_26")
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.label_47 = QtWidgets.QLabel(self.CSC_gb_12)
        self.label_47.setStyleSheet("color: rgb(0, 0, 0);")
        self.label_47.setObjectName("label_47")
        self.horizontalLayout_34.addWidget(self.label_47)
        self.CSC_H_LE = QtWidgets.QLineEdit(self.CSC_gb_12)
        self.CSC_H_LE.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.CSC_H_LE.setObjectName("CSC_H_LE")
        self.horizontalLayout_34.addWidget(self.CSC_H_LE)
        spacerItem3 = QtWidgets.QSpacerItem(108, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_34.addItem(spacerItem3)
        self.gridLayout_26.addLayout(self.horizontalLayout_34, 0, 0, 1, 1)
        self.verticalLayout_8.addWidget(self.CSC_gb_12)
        self.horizontalLayout.addWidget(self.frame_12)
        self.frame_13 = QtWidgets.QFrame(self.frame_11)
        self.frame_13.setMinimumSize(QtCore.QSize(380, 0))
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_13)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.CSC_gb_13 = QtWidgets.QGroupBox(self.frame_13)
        self.CSC_gb_13.setMinimumSize(QtCore.QSize(350, 0))
        font = QtGui.QFont()
        font.setItalic(False)
        font.setUnderline(False)
        self.CSC_gb_13.setFont(font)
        self.CSC_gb_13.setAutoFillBackground(False)
        self.CSC_gb_13.setStyleSheet("color: rgb(0, 0, 0);")
        self.CSC_gb_13.setFlat(False)
        self.CSC_gb_13.setCheckable(False)
        self.CSC_gb_13.setObjectName("CSC_gb_13")
        self.gridLayout_28 = QtWidgets.QGridLayout(self.CSC_gb_13)
        self.gridLayout_28.setObjectName("gridLayout_28")
        self.horizontalLayout_37 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_37.setObjectName("horizontalLayout_37")
        self.label_52 = QtWidgets.QLabel(self.CSC_gb_13)
        self.label_52.setObjectName("label_52")
        self.horizontalLayout_37.addWidget(self.label_52)
        self.CSVE_H_LE = QtWidgets.QLineEdit(self.CSC_gb_13)
        self.CSVE_H_LE.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.CSVE_H_LE.setObjectName("CSVE_H_LE")
        self.horizontalLayout_37.addWidget(self.CSVE_H_LE)
        spacerItem4 = QtWidgets.QSpacerItem(108, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_37.addItem(spacerItem4)
        self.gridLayout_28.addLayout(self.horizontalLayout_37, 0, 0, 1, 1)
        self.verticalLayout_6.addWidget(self.CSC_gb_13)
        self.horizontalLayout.addWidget(self.frame_13)
        self.frame_22 = QtWidgets.QFrame(self.frame_11)
        self.frame_22.setMinimumSize(QtCore.QSize(380, 0))
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_22)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.CSC_gb_22 = QtWidgets.QGroupBox(self.frame_22)
        self.CSC_gb_22.setMinimumSize(QtCore.QSize(350, 0))
        font = QtGui.QFont()
        font.setItalic(False)
        font.setUnderline(False)
        self.CSC_gb_22.setFont(font)
        self.CSC_gb_22.setAutoFillBackground(False)
        self.CSC_gb_22.setStyleSheet("color: rgb(0, 0, 0);")
        self.CSC_gb_22.setFlat(False)
        self.CSC_gb_22.setCheckable(False)
        self.CSC_gb_22.setObjectName("CSC_gb_22")
        self.gridLayout_46 = QtWidgets.QGridLayout(self.CSC_gb_22)
        self.gridLayout_46.setObjectName("gridLayout_46")
        self.horizontalLayout_61 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_61.setObjectName("horizontalLayout_61")
        self.label_87 = QtWidgets.QLabel(self.CSC_gb_22)
        self.label_87.setObjectName("label_87")
        self.horizontalLayout_61.addWidget(self.label_87)
        self.DVC_H_LE = QtWidgets.QLineEdit(self.CSC_gb_22)
        self.DVC_H_LE.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.DVC_H_LE.setObjectName("DVC_H_LE")
        self.horizontalLayout_61.addWidget(self.DVC_H_LE)
        spacerItem5 = QtWidgets.QSpacerItem(108, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_61.addItem(spacerItem5)
        self.gridLayout_46.addLayout(self.horizontalLayout_61, 0, 0, 1, 1)
        self.verticalLayout_5.addWidget(self.CSC_gb_22)
        self.horizontalLayout.addWidget(self.frame_22)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_20 = QtWidgets.QFrame(self.frame_11)
        self.frame_20.setMinimumSize(QtCore.QSize(380, 0))
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_20)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.CSC_gb_20 = QtWidgets.QGroupBox(self.frame_20)
        self.CSC_gb_20.setMinimumSize(QtCore.QSize(350, 0))
        font = QtGui.QFont()
        font.setItalic(False)
        font.setUnderline(False)
        self.CSC_gb_20.setFont(font)
        self.CSC_gb_20.setAutoFillBackground(False)
        self.CSC_gb_20.setStyleSheet("color: rgb(0, 0, 0);")
        self.CSC_gb_20.setFlat(False)
        self.CSC_gb_20.setCheckable(False)
        self.CSC_gb_20.setObjectName("CSC_gb_20")
        self.gridLayout_42 = QtWidgets.QGridLayout(self.CSC_gb_20)
        self.gridLayout_42.setObjectName("gridLayout_42")
        self.horizontalLayout_57 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_57.setObjectName("horizontalLayout_57")
        self.label_81 = QtWidgets.QLabel(self.CSC_gb_20)
        self.label_81.setObjectName("label_81")
        self.horizontalLayout_57.addWidget(self.label_81)
        self.CSIE1_H_LE = QtWidgets.QLineEdit(self.CSC_gb_20)
        self.CSIE1_H_LE.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.CSIE1_H_LE.setObjectName("CSIE1_H_LE")
        self.horizontalLayout_57.addWidget(self.CSIE1_H_LE)
        spacerItem6 = QtWidgets.QSpacerItem(108, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_57.addItem(spacerItem6)
        self.gridLayout_42.addLayout(self.horizontalLayout_57, 0, 0, 1, 1)
        self.verticalLayout_12.addWidget(self.CSC_gb_20)
        self.horizontalLayout_5.addWidget(self.frame_20)
        self.frame_21 = QtWidgets.QFrame(self.frame_11)
        self.frame_21.setMinimumSize(QtCore.QSize(380, 0))
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_21)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.CSC_gb_21 = QtWidgets.QGroupBox(self.frame_21)
        self.CSC_gb_21.setMinimumSize(QtCore.QSize(350, 0))
        font = QtGui.QFont()
        font.setItalic(False)
        font.setUnderline(False)
        self.CSC_gb_21.setFont(font)
        self.CSC_gb_21.setAutoFillBackground(False)
        self.CSC_gb_21.setStyleSheet("color: rgb(0, 0, 0);")
        self.CSC_gb_21.setFlat(False)
        self.CSC_gb_21.setCheckable(False)
        self.CSC_gb_21.setObjectName("CSC_gb_21")
        self.gridLayout_44 = QtWidgets.QGridLayout(self.CSC_gb_21)
        self.gridLayout_44.setObjectName("gridLayout_44")
        self.horizontalLayout_59 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_59.setObjectName("horizontalLayout_59")
        self.label_84 = QtWidgets.QLabel(self.CSC_gb_21)
        self.label_84.setObjectName("label_84")
        self.horizontalLayout_59.addWidget(self.label_84)
        self.CSIE2_H_LE = QtWidgets.QLineEdit(self.CSC_gb_21)
        self.CSIE2_H_LE.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.CSIE2_H_LE.setObjectName("CSIE2_H_LE")
        self.horizontalLayout_59.addWidget(self.CSIE2_H_LE)
        spacerItem7 = QtWidgets.QSpacerItem(108, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_59.addItem(spacerItem7)
        self.gridLayout_44.addLayout(self.horizontalLayout_59, 0, 0, 1, 1)
        self.verticalLayout_13.addWidget(self.CSC_gb_21)
        self.horizontalLayout_5.addWidget(self.frame_21)
        self.frame_27 = QtWidgets.QFrame(self.frame_11)
        self.frame_27.setMinimumSize(QtCore.QSize(380, 0))
        self.frame_27.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_27.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_27.setObjectName("frame_27")
        self.gridLayout_56 = QtWidgets.QGridLayout(self.frame_27)
        self.gridLayout_56.setObjectName("gridLayout_56")
        self.CSC_gb_27 = QtWidgets.QGroupBox(self.frame_27)
        self.CSC_gb_27.setMinimumSize(QtCore.QSize(350, 0))
        font = QtGui.QFont()
        font.setItalic(False)
        font.setUnderline(False)
        self.CSC_gb_27.setFont(font)
        self.CSC_gb_27.setAutoFillBackground(False)
        self.CSC_gb_27.setStyleSheet("color: rgb(0, 0, 0);")
        self.CSC_gb_27.setFlat(False)
        self.CSC_gb_27.setCheckable(False)
        self.CSC_gb_27.setObjectName("CSC_gb_27")
        self.gridLayout_57 = QtWidgets.QGridLayout(self.CSC_gb_27)
        self.gridLayout_57.setObjectName("gridLayout_57")
        self.horizontalLayout_71 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_71.setObjectName("horizontalLayout_71")
        self.label_109 = QtWidgets.QLabel(self.CSC_gb_27)
        self.label_109.setObjectName("label_109")
        self.horizontalLayout_71.addWidget(self.label_109)
        self.DVLR_H_LE = QtWidgets.QLineEdit(self.CSC_gb_27)
        self.DVLR_H_LE.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.DVLR_H_LE.setObjectName("DVLR_H_LE")
        self.horizontalLayout_71.addWidget(self.DVLR_H_LE)
        spacerItem8 = QtWidgets.QSpacerItem(108, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_71.addItem(spacerItem8)
        self.gridLayout_57.addLayout(self.horizontalLayout_71, 0, 0, 1, 1)
        self.gridLayout_56.addWidget(self.CSC_gb_27, 0, 0, 1, 1)
        self.horizontalLayout_5.addWidget(self.frame_27)
        self.gridLayout.addLayout(self.horizontalLayout_5, 4, 0, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.frame_30 = QtWidgets.QFrame(self.frame_11)
        self.frame_30.setMinimumSize(QtCore.QSize(380, 0))
        self.frame_30.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_30.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_30.setObjectName("frame_30")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frame_30)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.CSC_gb_28 = QtWidgets.QGroupBox(self.frame_30)
        self.CSC_gb_28.setMinimumSize(QtCore.QSize(350, 0))
        font = QtGui.QFont()
        font.setItalic(False)
        font.setUnderline(False)
        self.CSC_gb_28.setFont(font)
        self.CSC_gb_28.setAutoFillBackground(False)
        self.CSC_gb_28.setStyleSheet("color: rgb(0, 0, 0);")
        self.CSC_gb_28.setFlat(False)
        self.CSC_gb_28.setCheckable(False)
        self.CSC_gb_28.setObjectName("CSC_gb_28")
        self.gridLayout_55 = QtWidgets.QGridLayout(self.CSC_gb_28)
        self.gridLayout_55.setObjectName("gridLayout_55")
        self.horizontalLayout_69 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_69.setObjectName("horizontalLayout_69")
        self.label_96 = QtWidgets.QLabel(self.CSC_gb_28)
        self.label_96.setObjectName("label_96")
        self.horizontalLayout_69.addWidget(self.label_96)
        self.CSLR_H_LE = QtWidgets.QLineEdit(self.CSC_gb_28)
        self.CSLR_H_LE.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.CSLR_H_LE.setObjectName("CSLR_H_LE")
        self.horizontalLayout_69.addWidget(self.CSLR_H_LE)
        spacerItem9 = QtWidgets.QSpacerItem(108, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_69.addItem(spacerItem9)
        self.gridLayout_55.addLayout(self.horizontalLayout_69, 0, 0, 1, 1)
        self.verticalLayout_16.addWidget(self.CSC_gb_28)
        self.horizontalLayout_7.addWidget(self.frame_30)
        self.frame_31 = QtWidgets.QFrame(self.frame_11)
        self.frame_31.setMinimumSize(QtCore.QSize(380, 0))
        self.frame_31.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_31.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_31.setObjectName("frame_31")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.frame_31)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_17.addItem(spacerItem10)
        self.horizontalLayout_7.addWidget(self.frame_31)
        self.frame_32 = QtWidgets.QFrame(self.frame_11)
        self.frame_32.setMinimumSize(QtCore.QSize(380, 0))
        self.frame_32.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_32.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_32.setObjectName("frame_32")
        self.gridLayout_63 = QtWidgets.QGridLayout(self.frame_32)
        self.gridLayout_63.setObjectName("gridLayout_63")
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_63.addItem(spacerItem11, 0, 0, 1, 1)
        self.horizontalLayout_7.addWidget(self.frame_32)
        self.gridLayout.addLayout(self.horizontalLayout_7, 5, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_14 = QtWidgets.QFrame(self.frame_11)
        self.frame_14.setMinimumSize(QtCore.QSize(380, 0))
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_14)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.CSC_gb_14 = QtWidgets.QGroupBox(self.frame_14)
        self.CSC_gb_14.setMinimumSize(QtCore.QSize(350, 0))
        font = QtGui.QFont()
        font.setItalic(False)
        font.setUnderline(False)
        self.CSC_gb_14.setFont(font)
        self.CSC_gb_14.setAutoFillBackground(False)
        self.CSC_gb_14.setStyleSheet("color: rgb(0, 0, 0);")
        self.CSC_gb_14.setFlat(False)
        self.CSC_gb_14.setCheckable(False)
        self.CSC_gb_14.setObjectName("CSC_gb_14")
        self.gridLayout_30 = QtWidgets.QGridLayout(self.CSC_gb_14)
        self.gridLayout_30.setObjectName("gridLayout_30")
        self.horizontalLayout_39 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_39.setObjectName("horizontalLayout_39")
        self.label_53 = QtWidgets.QLabel(self.CSC_gb_14)
        self.label_53.setObjectName("label_53")
        self.horizontalLayout_39.addWidget(self.label_53)
        self.CSLS1_H_LE = QtWidgets.QLineEdit(self.CSC_gb_14)
        self.CSLS1_H_LE.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.CSLS1_H_LE.setObjectName("CSLS1_H_LE")
        self.horizontalLayout_39.addWidget(self.CSLS1_H_LE)
        spacerItem12 = QtWidgets.QSpacerItem(108, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_39.addItem(spacerItem12)
        self.gridLayout_30.addLayout(self.horizontalLayout_39, 0, 0, 1, 1)
        self.horizontalLayout_40 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_40.setObjectName("horizontalLayout_40")
        self.verticalLayout_39 = QtWidgets.QVBoxLayout()
        self.verticalLayout_39.setObjectName("verticalLayout_39")
        self.label_54 = QtWidgets.QLabel(self.CSC_gb_14)
        self.label_54.setObjectName("label_54")
        self.verticalLayout_39.addWidget(self.label_54)
        self.horizontalLayout_40.addLayout(self.verticalLayout_39)
        self.verticalLayout_40 = QtWidgets.QVBoxLayout()
        self.verticalLayout_40.setObjectName("verticalLayout_40")
        self.label_55 = QtWidgets.QLabel(self.CSC_gb_14)
        self.label_55.setObjectName("label_55")
        self.verticalLayout_40.addWidget(self.label_55)
        self.CSLS1_P1_LE = QtWidgets.QLineEdit(self.CSC_gb_14)
        self.CSLS1_P1_LE.setMinimumSize(QtCore.QSize(50, 0))
        self.CSLS1_P1_LE.setMaximumSize(QtCore.QSize(60, 16777215))
        self.CSLS1_P1_LE.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.CSLS1_P1_LE.setObjectName("CSLS1_P1_LE")
        self.verticalLayout_40.addWidget(self.CSLS1_P1_LE)
        self.horizontalLayout_40.addLayout(self.verticalLayout_40)
        self.verticalLayout_41 = QtWidgets.QVBoxLayout()
        self.verticalLayout_41.setObjectName("verticalLayout_41")
        self.label_56 = QtWidgets.QLabel(self.CSC_gb_14)
        self.label_56.setObjectName("label_56")
        self.verticalLayout_41.addWidget(self.label_56)
        self.CSLS1_P2_LE = QtWidgets.QLineEdit(self.CSC_gb_14)
        self.CSLS1_P2_LE.setMaximumSize(QtCore.QSize(60, 16777215))
        self.CSLS1_P2_LE.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.CSLS1_P2_LE.setObjectName("CSLS1_P2_LE")
        self.verticalLayout_41.addWidget(self.CSLS1_P2_LE)
        self.horizontalLayout_40.addLayout(self.verticalLayout_41)
        self.verticalLayout_42 = QtWidgets.QVBoxLayout()
        self.verticalLayout_42.setObjectName("verticalLayout_42")
        self.label_57 = QtWidgets.QLabel(self.CSC_gb_14)
        self.label_57.setObjectName("label_57")
        self.verticalLayout_42.addWidget(self.label_57)
        self.CSLS1_P3_LE = QtWidgets.QLineEdit(self.CSC_gb_14)
        self.CSLS1_P3_LE.setMaximumSize(QtCore.QSize(60, 16777215))
        self.CSLS1_P3_LE.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.CSLS1_P3_LE.setObjectName("CSLS1_P3_LE")
        self.verticalLayout_42.addWidget(self.CSLS1_P3_LE)
        self.horizontalLayout_40.addLayout(self.verticalLayout_42)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_40.addItem(spacerItem13)
        self.gridLayout_30.addLayout(self.horizontalLayout_40, 1, 0, 1, 1)
        self.verticalLayout_9.addWidget(self.CSC_gb_14)
        self.horizontalLayout_2.addWidget(self.frame_14)
        self.frame_15 = QtWidgets.QFrame(self.frame_11)
        self.frame_15.setMinimumSize(QtCore.QSize(380, 0))
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_15)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.CSC_gb_15 = QtWidgets.QGroupBox(self.frame_15)
        self.CSC_gb_15.setMinimumSize(QtCore.QSize(350, 0))
        font = QtGui.QFont()
        font.setItalic(False)
        font.setUnderline(False)
        self.CSC_gb_15.setFont(font)
        self.CSC_gb_15.setAutoFillBackground(False)
        self.CSC_gb_15.setStyleSheet("color: rgb(0, 0, 0);")
        self.CSC_gb_15.setFlat(False)
        self.CSC_gb_15.setCheckable(False)
        self.CSC_gb_15.setObjectName("CSC_gb_15")
        self.gridLayout_32 = QtWidgets.QGridLayout(self.CSC_gb_15)
        self.gridLayout_32.setObjectName("gridLayout_32")
        self.horizontalLayout_42 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_42.setObjectName("horizontalLayout_42")
        self.label_60 = QtWidgets.QLabel(self.CSC_gb_15)
        self.label_60.setObjectName("label_60")
        self.horizontalLayout_42.addWidget(self.label_60)
        self.CSLS2_H_LE = QtWidgets.QLineEdit(self.CSC_gb_15)
        self.CSLS2_H_LE.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.CSLS2_H_LE.setObjectName("CSLS2_H_LE")
        self.horizontalLayout_42.addWidget(self.CSLS2_H_LE)
        spacerItem14 = QtWidgets.QSpacerItem(108, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_42.addItem(spacerItem14)
        self.gridLayout_32.addLayout(self.horizontalLayout_42, 0, 0, 1, 1)
        self.horizontalLayout_43 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_43.setObjectName("horizontalLayout_43")
        self.verticalLayout_45 = QtWidgets.QVBoxLayout()
        self.verticalLayout_45.setObjectName("verticalLayout_45")
        self.label_61 = QtWidgets.QLabel(self.CSC_gb_15)
        self.label_61.setObjectName("label_61")
        self.verticalLayout_45.addWidget(self.label_61)
        self.horizontalLayout_43.addLayout(self.verticalLayout_45)
        self.verticalLayout_46 = QtWidgets.QVBoxLayout()
        self.verticalLayout_46.setObjectName("verticalLayout_46")
        self.label_62 = QtWidgets.QLabel(self.CSC_gb_15)
        self.label_62.setObjectName("label_62")
        self.verticalLayout_46.addWidget(self.label_62)
        self.CSLS2_P1_LE = QtWidgets.QLineEdit(self.CSC_gb_15)
        self.CSLS2_P1_LE.setMinimumSize(QtCore.QSize(50, 0))
        self.CSLS2_P1_LE.setMaximumSize(QtCore.QSize(60, 16777215))
        self.CSLS2_P1_LE.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.CSLS2_P1_LE.setObjectName("CSLS2_P1_LE")
        self.verticalLayout_46.addWidget(self.CSLS2_P1_LE)
        self.horizontalLayout_43.addLayout(self.verticalLayout_46)
        self.verticalLayout_47 = QtWidgets.QVBoxLayout()
        self.verticalLayout_47.setObjectName("verticalLayout_47")
        self.label_63 = QtWidgets.QLabel(self.CSC_gb_15)
        self.label_63.setObjectName("label_63")
        self.verticalLayout_47.addWidget(self.label_63)
        self.CSLS2_P2_LE = QtWidgets.QLineEdit(self.CSC_gb_15)
        self.CSLS2_P2_LE.setMaximumSize(QtCore.QSize(60, 16777215))
        self.CSLS2_P2_LE.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.CSLS2_P2_LE.setObjectName("CSLS2_P2_LE")
        self.verticalLayout_47.addWidget(self.CSLS2_P2_LE)
        self.horizontalLayout_43.addLayout(self.verticalLayout_47)
        self.verticalLayout_48 = QtWidgets.QVBoxLayout()
        self.verticalLayout_48.setObjectName("verticalLayout_48")
        self.label_64 = QtWidgets.QLabel(self.CSC_gb_15)
        self.label_64.setObjectName("label_64")
        self.verticalLayout_48.addWidget(self.label_64)
        self.CSLS2_P3_LE = QtWidgets.QLineEdit(self.CSC_gb_15)
        self.CSLS2_P3_LE.setMaximumSize(QtCore.QSize(60, 16777215))
        self.CSLS2_P3_LE.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.CSLS2_P3_LE.setObjectName("CSLS2_P3_LE")
        self.verticalLayout_48.addWidget(self.CSLS2_P3_LE)
        self.horizontalLayout_43.addLayout(self.verticalLayout_48)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_43.addItem(spacerItem15)
        self.gridLayout_32.addLayout(self.horizontalLayout_43, 1, 0, 1, 1)
        self.verticalLayout_7.addWidget(self.CSC_gb_15)
        self.horizontalLayout_2.addWidget(self.frame_15)
        self.frame_24 = QtWidgets.QFrame(self.frame_11)
        self.frame_24.setMinimumSize(QtCore.QSize(380, 0))
        self.frame_24.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_24.setObjectName("frame_24")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_24)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.CSC_gb_23 = QtWidgets.QGroupBox(self.frame_24)
        self.CSC_gb_23.setMinimumSize(QtCore.QSize(350, 0))
        font = QtGui.QFont()
        font.setItalic(False)
        font.setUnderline(False)
        self.CSC_gb_23.setFont(font)
        self.CSC_gb_23.setAutoFillBackground(False)
        self.CSC_gb_23.setStyleSheet("color: rgb(0, 0, 0);")
        self.CSC_gb_23.setFlat(False)
        self.CSC_gb_23.setCheckable(False)
        self.CSC_gb_23.setObjectName("CSC_gb_23")
        self.gridLayout_49 = QtWidgets.QGridLayout(self.CSC_gb_23)
        self.gridLayout_49.setObjectName("gridLayout_49")
        self.horizontalLayout_45 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_45.setObjectName("horizontalLayout_45")
        self.label_88 = QtWidgets.QLabel(self.CSC_gb_23)
        self.label_88.setObjectName("label_88")
        self.horizontalLayout_45.addWidget(self.label_88)
        self.DVLS_H_LE = QtWidgets.QLineEdit(self.CSC_gb_23)
        self.DVLS_H_LE.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.DVLS_H_LE.setObjectName("DVLS_H_LE")
        self.horizontalLayout_45.addWidget(self.DVLS_H_LE)
        spacerItem16 = QtWidgets.QSpacerItem(108, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_45.addItem(spacerItem16)
        self.gridLayout_49.addLayout(self.horizontalLayout_45, 0, 0, 1, 1)
        self.horizontalLayout_50 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_50.setObjectName("horizontalLayout_50")
        self.verticalLayout_65 = QtWidgets.QVBoxLayout()
        self.verticalLayout_65.setObjectName("verticalLayout_65")
        self.label_89 = QtWidgets.QLabel(self.CSC_gb_23)
        self.label_89.setObjectName("label_89")
        self.verticalLayout_65.addWidget(self.label_89)
        self.horizontalLayout_50.addLayout(self.verticalLayout_65)
        self.verticalLayout_66 = QtWidgets.QVBoxLayout()
        self.verticalLayout_66.setObjectName("verticalLayout_66")
        self.label_90 = QtWidgets.QLabel(self.CSC_gb_23)
        self.label_90.setObjectName("label_90")
        self.verticalLayout_66.addWidget(self.label_90)
        self.DVLS_P1_LE = QtWidgets.QLineEdit(self.CSC_gb_23)
        self.DVLS_P1_LE.setMinimumSize(QtCore.QSize(50, 0))
        self.DVLS_P1_LE.setMaximumSize(QtCore.QSize(60, 16777215))
        self.DVLS_P1_LE.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.DVLS_P1_LE.setObjectName("DVLS_P1_LE")
        self.verticalLayout_66.addWidget(self.DVLS_P1_LE)
        self.horizontalLayout_50.addLayout(self.verticalLayout_66)
        self.verticalLayout_67 = QtWidgets.QVBoxLayout()
        self.verticalLayout_67.setObjectName("verticalLayout_67")
        self.label_91 = QtWidgets.QLabel(self.CSC_gb_23)
        self.label_91.setObjectName("label_91")
        self.verticalLayout_67.addWidget(self.label_91)
        self.DVLS_P2_LE = QtWidgets.QLineEdit(self.CSC_gb_23)
        self.DVLS_P2_LE.setMaximumSize(QtCore.QSize(60, 16777215))
        self.DVLS_P2_LE.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.DVLS_P2_LE.setObjectName("DVLS_P2_LE")
        self.verticalLayout_67.addWidget(self.DVLS_P2_LE)
        self.horizontalLayout_50.addLayout(self.verticalLayout_67)
        self.verticalLayout_68 = QtWidgets.QVBoxLayout()
        self.verticalLayout_68.setObjectName("verticalLayout_68")
        self.label_92 = QtWidgets.QLabel(self.CSC_gb_23)
        self.label_92.setObjectName("label_92")
        self.verticalLayout_68.addWidget(self.label_92)
        self.DVLS_P3_LE = QtWidgets.QLineEdit(self.CSC_gb_23)
        self.DVLS_P3_LE.setMaximumSize(QtCore.QSize(60, 16777215))
        self.DVLS_P3_LE.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.DVLS_P3_LE.setObjectName("DVLS_P3_LE")
        self.verticalLayout_68.addWidget(self.DVLS_P3_LE)
        self.horizontalLayout_50.addLayout(self.verticalLayout_68)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_50.addItem(spacerItem17)
        self.gridLayout_49.addLayout(self.horizontalLayout_50, 1, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.CSC_gb_23)
        self.horizontalLayout_2.addWidget(self.frame_24)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_16 = QtWidgets.QFrame(self.frame_11)
        self.frame_16.setMinimumSize(QtCore.QSize(380, 0))
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_16)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.CSC_gb_16 = QtWidgets.QGroupBox(self.frame_16)
        self.CSC_gb_16.setMinimumSize(QtCore.QSize(350, 0))
        font = QtGui.QFont()
        font.setItalic(False)
        font.setUnderline(False)
        self.CSC_gb_16.setFont(font)
        self.CSC_gb_16.setAutoFillBackground(False)
        self.CSC_gb_16.setStyleSheet("color: rgb(0, 0, 0);")
        self.CSC_gb_16.setFlat(False)
        self.CSC_gb_16.setCheckable(False)
        self.CSC_gb_16.setObjectName("CSC_gb_16")
        self.gridLayout_34 = QtWidgets.QGridLayout(self.CSC_gb_16)
        self.gridLayout_34.setObjectName("gridLayout_34")
        self.horizontalLayout_47 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_47.setObjectName("horizontalLayout_47")
        self.label_69 = QtWidgets.QLabel(self.CSC_gb_16)
        self.label_69.setObjectName("label_69")
        self.horizontalLayout_47.addWidget(self.label_69)
        self.CSVG_H_LE = QtWidgets.QLineEdit(self.CSC_gb_16)
        self.CSVG_H_LE.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.CSVG_H_LE.setObjectName("CSVG_H_LE")
        self.horizontalLayout_47.addWidget(self.CSVG_H_LE)
        spacerItem18 = QtWidgets.QSpacerItem(108, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_47.addItem(spacerItem18)
        self.gridLayout_34.addLayout(self.horizontalLayout_47, 0, 0, 1, 1)
        self.verticalLayout_10.addWidget(self.CSC_gb_16)
        self.horizontalLayout_3.addWidget(self.frame_16)
        self.frame_17 = QtWidgets.QFrame(self.frame_11)
        self.frame_17.setMinimumSize(QtCore.QSize(380, 0))
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_17)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.CSC_gb_17 = QtWidgets.QGroupBox(self.frame_17)
        self.CSC_gb_17.setMinimumSize(QtCore.QSize(350, 0))
        font = QtGui.QFont()
        font.setItalic(False)
        font.setUnderline(False)
        self.CSC_gb_17.setFont(font)
        self.CSC_gb_17.setAutoFillBackground(False)
        self.CSC_gb_17.setStyleSheet("color: rgb(0, 0, 0);")
        self.CSC_gb_17.setFlat(False)
        self.CSC_gb_17.setCheckable(False)
        self.CSC_gb_17.setObjectName("CSC_gb_17")
        self.gridLayout_36 = QtWidgets.QGridLayout(self.CSC_gb_17)
        self.gridLayout_36.setObjectName("gridLayout_36")
        self.horizontalLayout_49 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_49.setObjectName("horizontalLayout_49")
        self.label_72 = QtWidgets.QLabel(self.CSC_gb_17)
        self.label_72.setObjectName("label_72")
        self.horizontalLayout_49.addWidget(self.label_72)
        self.CSIL_H_LE = QtWidgets.QLineEdit(self.CSC_gb_17)
        self.CSIL_H_LE.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.CSIL_H_LE.setObjectName("CSIL_H_LE")
        self.horizontalLayout_49.addWidget(self.CSIL_H_LE)
        spacerItem19 = QtWidgets.QSpacerItem(108, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_49.addItem(spacerItem19)
        self.gridLayout_36.addLayout(self.horizontalLayout_49, 0, 0, 1, 1)
        self.verticalLayout_11.addWidget(self.CSC_gb_17)
        self.horizontalLayout_3.addWidget(self.frame_17)
        self.frame_23 = QtWidgets.QFrame(self.frame_11)
        self.frame_23.setMinimumSize(QtCore.QSize(380, 0))
        self.frame_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_23)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.CSC_gb_24 = QtWidgets.QGroupBox(self.frame_23)
        self.CSC_gb_24.setMinimumSize(QtCore.QSize(350, 0))
        font = QtGui.QFont()
        font.setItalic(False)
        font.setUnderline(False)
        self.CSC_gb_24.setFont(font)
        self.CSC_gb_24.setAutoFillBackground(False)
        self.CSC_gb_24.setStyleSheet("color: rgb(0, 0, 0);")
        self.CSC_gb_24.setFlat(False)
        self.CSC_gb_24.setCheckable(False)
        self.CSC_gb_24.setObjectName("CSC_gb_24")
        self.gridLayout_50 = QtWidgets.QGridLayout(self.CSC_gb_24)
        self.gridLayout_50.setObjectName("gridLayout_50")
        self.horizontalLayout_63 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_63.setObjectName("horizontalLayout_63")
        self.label_97 = QtWidgets.QLabel(self.CSC_gb_24)
        self.label_97.setObjectName("label_97")
        self.horizontalLayout_63.addWidget(self.label_97)
        self.DVVER_H_LE = QtWidgets.QLineEdit(self.CSC_gb_24)
        self.DVVER_H_LE.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.DVVER_H_LE.setObjectName("DVVER_H_LE")
        self.horizontalLayout_63.addWidget(self.DVVER_H_LE)
        spacerItem20 = QtWidgets.QSpacerItem(108, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_63.addItem(spacerItem20)
        self.gridLayout_50.addLayout(self.horizontalLayout_63, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.CSC_gb_24)
        self.horizontalLayout_3.addWidget(self.frame_23)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame_11, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.tab_2)
        self.scrollArea_2.setGeometry(QtCore.QRect(-20, -20, 1281, 701))
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 1279, 699))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.scrollAreaWidgetContents_3)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 1259, 679))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.frame_26 = QtWidgets.QFrame(self.scrollAreaWidgetContents_4)
        self.frame_26.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_26.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_26.setObjectName("frame_26")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_26)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.frame_28 = QtWidgets.QFrame(self.frame_26)
        self.frame_28.setMinimumSize(QtCore.QSize(380, 0))
        self.frame_28.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_28.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_28.setObjectName("frame_28")
        self.CSC_gb_26 = QtWidgets.QGroupBox(self.frame_28)
        self.CSC_gb_26.setGeometry(QtCore.QRect(10, 10, 381, 83))
        self.CSC_gb_26.setMinimumSize(QtCore.QSize(350, 0))
        font = QtGui.QFont()
        font.setItalic(False)
        font.setUnderline(False)
        self.CSC_gb_26.setFont(font)
        self.CSC_gb_26.setAutoFillBackground(True)
        self.CSC_gb_26.setFlat(False)
        self.CSC_gb_26.setCheckable(False)
        self.CSC_gb_26.setObjectName("CSC_gb_26")
        self.layoutWidget = QtWidgets.QWidget(self.CSC_gb_26)
        self.layoutWidget.setGeometry(QtCore.QRect(11, 24, 361, 43))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.verticalLayout_77 = QtWidgets.QVBoxLayout()
        self.verticalLayout_77.setObjectName("verticalLayout_77")
        self.label_104 = QtWidgets.QLabel(self.layoutWidget)
        self.label_104.setObjectName("label_104")
        self.verticalLayout_77.addWidget(self.label_104)
        self.CSLR_V_LE = QtWidgets.QLineEdit(self.layoutWidget)
        self.CSLR_V_LE.setMinimumSize(QtCore.QSize(210, 0))
        self.CSLR_V_LE.setMaximumSize(QtCore.QSize(350, 16777215))
        self.CSLR_V_LE.setObjectName("CSLR_V_LE")
        self.verticalLayout_77.addWidget(self.CSLR_V_LE)
        self.gridLayout_10.addLayout(self.verticalLayout_77, 0, 0, 1, 1)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_105 = QtWidgets.QLabel(self.layoutWidget)
        self.label_105.setObjectName("label_105")
        self.gridLayout_7.addWidget(self.label_105, 0, 0, 1, 1)
        self.CSLR_D_LE = QtWidgets.QLineEdit(self.layoutWidget)
        self.CSLR_D_LE.setMinimumSize(QtCore.QSize(50, 0))
        self.CSLR_D_LE.setMaximumSize(QtCore.QSize(100, 16777215))
        self.CSLR_D_LE.setObjectName("CSLR_D_LE")
        self.gridLayout_7.addWidget(self.CSLR_D_LE, 1, 0, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_7, 0, 1, 1, 1)
        self.gridLayout_6.addWidget(self.frame_28, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_6, 5, 0, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_29 = QtWidgets.QFrame(self.frame_26)
        self.frame_29.setMinimumSize(QtCore.QSize(380, 0))
        self.frame_29.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_29.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_29.setObjectName("frame_29")
        self.gridLayout_39 = QtWidgets.QGridLayout(self.frame_29)
        self.gridLayout_39.setObjectName("gridLayout_39")
        self.CSC_gb_29 = QtWidgets.QGroupBox(self.frame_29)
        self.CSC_gb_29.setMinimumSize(QtCore.QSize(350, 0))
        font = QtGui.QFont()
        font.setItalic(False)
        font.setUnderline(False)
        self.CSC_gb_29.setFont(font)
        self.CSC_gb_29.setAutoFillBackground(True)
        self.CSC_gb_29.setFlat(False)
        self.CSC_gb_29.setCheckable(False)
        self.CSC_gb_29.setObjectName("CSC_gb_29")
        self.gridLayout_41 = QtWidgets.QGridLayout(self.CSC_gb_29)
        self.gridLayout_41.setObjectName("gridLayout_41")
        self.horizontalLayout_51 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_51.setObjectName("horizontalLayout_51")
        self.verticalLayout_55 = QtWidgets.QVBoxLayout()
        self.verticalLayout_55.setObjectName("verticalLayout_55")
        self.label_73 = QtWidgets.QLabel(self.CSC_gb_29)
        self.label_73.setObjectName("label_73")
        self.verticalLayout_55.addWidget(self.label_73)
        self.CSTID_V_LE = QtWidgets.QLineEdit(self.CSC_gb_29)
        self.CSTID_V_LE.setMinimumSize(QtCore.QSize(210, 0))
        self.CSTID_V_LE.setMaximumSize(QtCore.QSize(350, 16777215))
        self.CSTID_V_LE.setObjectName("CSTID_V_LE")
        self.verticalLayout_55.addWidget(self.CSTID_V_LE)
        self.horizontalLayout_51.addLayout(self.verticalLayout_55)
        self.verticalLayout_56 = QtWidgets.QVBoxLayout()
        self.verticalLayout_56.setObjectName("verticalLayout_56")
        self.label_74 = QtWidgets.QLabel(self.CSC_gb_29)
        self.label_74.setObjectName("label_74")
        self.verticalLayout_56.addWidget(self.label_74)
        self.CSTID_D_LE = QtWidgets.QLineEdit(self.CSC_gb_29)
        self.CSTID_D_LE.setMinimumSize(QtCore.QSize(50, 0))
        self.CSTID_D_LE.setMaximumSize(QtCore.QSize(100, 16777215))
        self.CSTID_D_LE.setObjectName("CSTID_D_LE")
        self.verticalLayout_56.addWidget(self.CSTID_D_LE)
        self.horizontalLayout_51.addLayout(self.verticalLayout_56)
        self.gridLayout_41.addLayout(self.horizontalLayout_51, 0, 0, 1, 1)
        self.gridLayout_39.addWidget(self.CSC_gb_29, 0, 0, 1, 1)
        self.horizontalLayout_6.addWidget(self.frame_29)
        self.frame_33 = QtWidgets.QFrame(self.frame_26)
        self.frame_33.setMinimumSize(QtCore.QSize(380, 0))
        self.frame_33.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_33.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_33.setObjectName("frame_33")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_33)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.CSC_gb_30 = QtWidgets.QGroupBox(self.frame_33)
        self.CSC_gb_30.setMinimumSize(QtCore.QSize(350, 0))
        font = QtGui.QFont()
        font.setItalic(False)
        font.setUnderline(False)
        self.CSC_gb_30.setFont(font)
        self.CSC_gb_30.setAutoFillBackground(True)
        self.CSC_gb_30.setFlat(False)
        self.CSC_gb_30.setCheckable(False)
        self.CSC_gb_30.setObjectName("CSC_gb_30")
        self.gridLayout_43 = QtWidgets.QGridLayout(self.CSC_gb_30)
        self.gridLayout_43.setObjectName("gridLayout_43")
        self.horizontalLayout_55 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_55.setObjectName("horizontalLayout_55")
        self.verticalLayout_57 = QtWidgets.QVBoxLayout()
        self.verticalLayout_57.setObjectName("verticalLayout_57")
        self.label_77 = QtWidgets.QLabel(self.CSC_gb_30)
        self.label_77.setObjectName("label_77")
        self.verticalLayout_57.addWidget(self.label_77)
        self.CSVP_V_LE_2 = QtWidgets.QLineEdit(self.CSC_gb_30)
        self.CSVP_V_LE_2.setMinimumSize(QtCore.QSize(210, 0))
        self.CSVP_V_LE_2.setMaximumSize(QtCore.QSize(350, 16777215))
        self.CSVP_V_LE_2.setObjectName("CSVP_V_LE_2")
        self.verticalLayout_57.addWidget(self.CSVP_V_LE_2)
        self.horizontalLayout_55.addLayout(self.verticalLayout_57)
        self.verticalLayout_58 = QtWidgets.QVBoxLayout()
        self.verticalLayout_58.setObjectName("verticalLayout_58")
        self.label_79 = QtWidgets.QLabel(self.CSC_gb_30)
        self.label_79.setObjectName("label_79")
        self.verticalLayout_58.addWidget(self.label_79)
        self.CSVP_D_LE_2 = QtWidgets.QLineEdit(self.CSC_gb_30)
        self.CSVP_D_LE_2.setMinimumSize(QtCore.QSize(50, 0))
        self.CSVP_D_LE_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.CSVP_D_LE_2.setObjectName("CSVP_D_LE_2")
        self.verticalLayout_58.addWidget(self.CSVP_D_LE_2)
        self.horizontalLayout_55.addLayout(self.verticalLayout_58)
        self.gridLayout_43.addLayout(self.horizontalLayout_55, 0, 0, 1, 1)
        self.verticalLayout_15.addWidget(self.CSC_gb_30)
        self.horizontalLayout_6.addWidget(self.frame_33)
        self.frame_34 = QtWidgets.QFrame(self.frame_26)
        self.frame_34.setMinimumSize(QtCore.QSize(380, 0))
        self.frame_34.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_34.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_34.setObjectName("frame_34")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.frame_34)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.CSC_gb_31 = QtWidgets.QGroupBox(self.frame_34)
        self.CSC_gb_31.setMinimumSize(QtCore.QSize(350, 0))
        font = QtGui.QFont()
        font.setItalic(False)
        font.setUnderline(False)
        self.CSC_gb_31.setFont(font)
        self.CSC_gb_31.setAutoFillBackground(True)
        self.CSC_gb_31.setFlat(False)
        self.CSC_gb_31.setCheckable(False)
        self.CSC_gb_31.setObjectName("CSC_gb_31")
        self.gridLayout_53 = QtWidgets.QGridLayout(self.CSC_gb_31)
        self.gridLayout_53.setObjectName("gridLayout_53")
        self.horizontalLayout_64 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_64.setObjectName("horizontalLayout_64")
        self.verticalLayout_73 = QtWidgets.QVBoxLayout()
        self.verticalLayout_73.setObjectName("verticalLayout_73")
        self.label_98 = QtWidgets.QLabel(self.CSC_gb_31)
        self.label_98.setObjectName("label_98")
        self.verticalLayout_73.addWidget(self.label_98)
        self.DVVP_V_LE = QtWidgets.QLineEdit(self.CSC_gb_31)
        self.DVVP_V_LE.setMinimumSize(QtCore.QSize(210, 0))
        self.DVVP_V_LE.setMaximumSize(QtCore.QSize(350, 16777215))
        self.DVVP_V_LE.setObjectName("DVVP_V_LE")
        self.verticalLayout_73.addWidget(self.DVVP_V_LE)
        self.horizontalLayout_64.addLayout(self.verticalLayout_73)
        self.verticalLayout_74 = QtWidgets.QVBoxLayout()
        self.verticalLayout_74.setObjectName("verticalLayout_74")
        self.label_99 = QtWidgets.QLabel(self.CSC_gb_31)
        self.label_99.setObjectName("label_99")
        self.verticalLayout_74.addWidget(self.label_99)
        self.DVVP_D_LE = QtWidgets.QLineEdit(self.CSC_gb_31)
        self.DVVP_D_LE.setMinimumSize(QtCore.QSize(50, 0))
        self.DVVP_D_LE.setMaximumSize(QtCore.QSize(100, 16777215))
        self.DVVP_D_LE.setObjectName("DVVP_D_LE")
        self.verticalLayout_74.addWidget(self.DVVP_D_LE)
        self.horizontalLayout_64.addLayout(self.verticalLayout_74)
        self.gridLayout_53.addLayout(self.horizontalLayout_64, 0, 0, 1, 1)
        self.verticalLayout_18.addWidget(self.CSC_gb_31)
        self.horizontalLayout_6.addWidget(self.frame_34)
        self.gridLayout_2.addLayout(self.horizontalLayout_6, 3, 0, 1, 1)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.frame_35 = QtWidgets.QFrame(self.frame_26)
        self.frame_35.setMinimumSize(QtCore.QSize(380, 0))
        self.frame_35.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_35.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_35.setObjectName("frame_35")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.frame_35)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.CSC_gb_32 = QtWidgets.QGroupBox(self.frame_35)
        self.CSC_gb_32.setMinimumSize(QtCore.QSize(350, 0))
        font = QtGui.QFont()
        font.setItalic(False)
        font.setUnderline(False)
        self.CSC_gb_32.setFont(font)
        self.CSC_gb_32.setAutoFillBackground(True)
        self.CSC_gb_32.setFlat(False)
        self.CSC_gb_32.setCheckable(False)
        self.CSC_gb_32.setObjectName("CSC_gb_32")
        self.gridLayout_27 = QtWidgets.QGridLayout(self.CSC_gb_32)
        self.gridLayout_27.setObjectName("gridLayout_27")
        self.horizontalLayout_36 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_36.setObjectName("horizontalLayout_36")
        self.verticalLayout_35 = QtWidgets.QVBoxLayout()
        self.verticalLayout_35.setObjectName("verticalLayout_35")
        self.label_49 = QtWidgets.QLabel(self.CSC_gb_32)
        self.label_49.setObjectName("label_49")
        self.verticalLayout_35.addWidget(self.label_49)
        self.CSC_V_LE = QtWidgets.QLineEdit(self.CSC_gb_32)
        self.CSC_V_LE.setMinimumSize(QtCore.QSize(210, 0))
        self.CSC_V_LE.setMaximumSize(QtCore.QSize(350, 16777215))
        self.CSC_V_LE.setObjectName("CSC_V_LE")
        self.verticalLayout_35.addWidget(self.CSC_V_LE)
        self.horizontalLayout_36.addLayout(self.verticalLayout_35)
        self.verticalLayout_36 = QtWidgets.QVBoxLayout()
        self.verticalLayout_36.setObjectName("verticalLayout_36")
        self.label_50 = QtWidgets.QLabel(self.CSC_gb_32)
        self.label_50.setObjectName("label_50")
        self.verticalLayout_36.addWidget(self.label_50)
        self.CSC_D_LE = QtWidgets.QLineEdit(self.CSC_gb_32)
        self.CSC_D_LE.setMinimumSize(QtCore.QSize(50, 0))
        self.CSC_D_LE.setMaximumSize(QtCore.QSize(100, 16777215))
        self.CSC_D_LE.setObjectName("CSC_D_LE")
        self.verticalLayout_36.addWidget(self.CSC_D_LE)
        self.horizontalLayout_36.addLayout(self.verticalLayout_36)
        self.gridLayout_27.addLayout(self.horizontalLayout_36, 0, 0, 1, 1)
        self.verticalLayout_19.addWidget(self.CSC_gb_32)
        self.horizontalLayout_8.addWidget(self.frame_35)
        self.frame_36 = QtWidgets.QFrame(self.frame_26)
        self.frame_36.setMinimumSize(QtCore.QSize(380, 0))
        self.frame_36.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_36.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_36.setObjectName("frame_36")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.frame_36)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.CSC_gb_33 = QtWidgets.QGroupBox(self.frame_36)
        self.CSC_gb_33.setMinimumSize(QtCore.QSize(350, 0))
        font = QtGui.QFont()
        font.setItalic(False)
        font.setUnderline(False)
        self.CSC_gb_33.setFont(font)
        self.CSC_gb_33.setAutoFillBackground(True)
        self.CSC_gb_33.setFlat(False)
        self.CSC_gb_33.setCheckable(False)
        self.CSC_gb_33.setObjectName("CSC_gb_33")
        self.gridLayout_29 = QtWidgets.QGridLayout(self.CSC_gb_33)
        self.gridLayout_29.setObjectName("gridLayout_29")
        self.horizontalLayout_38 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_38.setObjectName("horizontalLayout_38")
        self.verticalLayout_37 = QtWidgets.QVBoxLayout()
        self.verticalLayout_37.setObjectName("verticalLayout_37")
        self.label_51 = QtWidgets.QLabel(self.CSC_gb_33)
        self.label_51.setObjectName("label_51")
        self.verticalLayout_37.addWidget(self.label_51)
        self.CSVE_V_LE = QtWidgets.QLineEdit(self.CSC_gb_33)
        self.CSVE_V_LE.setMinimumSize(QtCore.QSize(210, 0))
        self.CSVE_V_LE.setMaximumSize(QtCore.QSize(350, 16777215))
        self.CSVE_V_LE.setObjectName("CSVE_V_LE")
        self.verticalLayout_37.addWidget(self.CSVE_V_LE)
        self.horizontalLayout_38.addLayout(self.verticalLayout_37)
        self.verticalLayout_38 = QtWidgets.QVBoxLayout()
        self.verticalLayout_38.setObjectName("verticalLayout_38")
        self.label_58 = QtWidgets.QLabel(self.CSC_gb_33)
        self.label_58.setObjectName("label_58")
        self.verticalLayout_38.addWidget(self.label_58)
        self.CSVE_D_LE = QtWidgets.QLineEdit(self.CSC_gb_33)
        self.CSVE_D_LE.setMinimumSize(QtCore.QSize(50, 0))
        self.CSVE_D_LE.setMaximumSize(QtCore.QSize(100, 16777215))
        self.CSVE_D_LE.setObjectName("CSVE_D_LE")
        self.verticalLayout_38.addWidget(self.CSVE_D_LE)
        self.horizontalLayout_38.addLayout(self.verticalLayout_38)
        self.gridLayout_29.addLayout(self.horizontalLayout_38, 0, 0, 1, 1)
        self.verticalLayout_20.addWidget(self.CSC_gb_33)
        self.horizontalLayout_8.addWidget(self.frame_36)
        self.frame_37 = QtWidgets.QFrame(self.frame_26)
        self.frame_37.setMinimumSize(QtCore.QSize(380, 0))
        self.frame_37.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_37.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_37.setObjectName("frame_37")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.frame_37)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.CSC_gb_34 = QtWidgets.QGroupBox(self.frame_37)
        self.CSC_gb_34.setMinimumSize(QtCore.QSize(350, 0))
        font = QtGui.QFont()
        font.setItalic(False)
        font.setUnderline(False)
        self.CSC_gb_34.setFont(font)
        self.CSC_gb_34.setAutoFillBackground(True)
        self.CSC_gb_34.setFlat(False)
        self.CSC_gb_34.setCheckable(False)
        self.CSC_gb_34.setObjectName("CSC_gb_34")
        self.gridLayout_47 = QtWidgets.QGridLayout(self.CSC_gb_34)
        self.gridLayout_47.setObjectName("gridLayout_47")
        self.horizontalLayout_60 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_60.setObjectName("horizontalLayout_60")
        self.verticalLayout_63 = QtWidgets.QVBoxLayout()
        self.verticalLayout_63.setObjectName("verticalLayout_63")
        self.label_85 = QtWidgets.QLabel(self.CSC_gb_34)
        self.label_85.setObjectName("label_85")
        self.verticalLayout_63.addWidget(self.label_85)
        self.DVC_V_LE = QtWidgets.QLineEdit(self.CSC_gb_34)
        self.DVC_V_LE.setMinimumSize(QtCore.QSize(210, 0))
        self.DVC_V_LE.setMaximumSize(QtCore.QSize(350, 16777215))
        self.DVC_V_LE.setObjectName("DVC_V_LE")
        self.verticalLayout_63.addWidget(self.DVC_V_LE)
        self.horizontalLayout_60.addLayout(self.verticalLayout_63)
        self.verticalLayout_64 = QtWidgets.QVBoxLayout()
        self.verticalLayout_64.setObjectName("verticalLayout_64")
        self.label_86 = QtWidgets.QLabel(self.CSC_gb_34)
        self.label_86.setObjectName("label_86")
        self.verticalLayout_64.addWidget(self.label_86)
        self.DVC_D_LE = QtWidgets.QLineEdit(self.CSC_gb_34)
        self.DVC_D_LE.setMinimumSize(QtCore.QSize(50, 0))
        self.DVC_D_LE.setMaximumSize(QtCore.QSize(100, 16777215))
        self.DVC_D_LE.setObjectName("DVC_D_LE")
        self.verticalLayout_64.addWidget(self.DVC_D_LE)
        self.horizontalLayout_60.addLayout(self.verticalLayout_64)
        self.gridLayout_47.addLayout(self.horizontalLayout_60, 0, 0, 1, 1)
        self.verticalLayout_21.addWidget(self.CSC_gb_34)
        self.horizontalLayout_8.addWidget(self.frame_37)
        self.gridLayout_2.addLayout(self.horizontalLayout_8, 0, 0, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.frame_38 = QtWidgets.QFrame(self.frame_26)
        self.frame_38.setMinimumSize(QtCore.QSize(380, 0))
        self.frame_38.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_38.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_38.setObjectName("frame_38")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.frame_38)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.CSC_gb_35 = QtWidgets.QGroupBox(self.frame_38)
        self.CSC_gb_35.setMinimumSize(QtCore.QSize(350, 0))
        font = QtGui.QFont()
        font.setItalic(False)
        font.setUnderline(False)
        self.CSC_gb_35.setFont(font)
        self.CSC_gb_35.setAutoFillBackground(True)
        self.CSC_gb_35.setFlat(False)
        self.CSC_gb_35.setCheckable(False)
        self.CSC_gb_35.setObjectName("CSC_gb_35")
        self.gridLayout_31 = QtWidgets.QGridLayout(self.CSC_gb_35)
        self.gridLayout_31.setObjectName("gridLayout_31")
        self.horizontalLayout_46 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_46.setObjectName("horizontalLayout_46")
        self.verticalLayout_43 = QtWidgets.QVBoxLayout()
        self.verticalLayout_43.setObjectName("verticalLayout_43")
        self.label_66 = QtWidgets.QLabel(self.CSC_gb_35)
        self.label_66.setObjectName("label_66")
        self.verticalLayout_43.addWidget(self.label_66)
        self.CSLS1_V_LE = QtWidgets.QLineEdit(self.CSC_gb_35)
        self.CSLS1_V_LE.setMinimumSize(QtCore.QSize(210, 0))
        self.CSLS1_V_LE.setMaximumSize(QtCore.QSize(350, 16777215))
        self.CSLS1_V_LE.setObjectName("CSLS1_V_LE")
        self.verticalLayout_43.addWidget(self.CSLS1_V_LE)
        self.horizontalLayout_46.addLayout(self.verticalLayout_43)
        self.verticalLayout_44 = QtWidgets.QVBoxLayout()
        self.verticalLayout_44.setObjectName("verticalLayout_44")
        self.label_67 = QtWidgets.QLabel(self.CSC_gb_35)
        self.label_67.setObjectName("label_67")
        self.verticalLayout_44.addWidget(self.label_67)
        self.CSLS1_D_LE = QtWidgets.QLineEdit(self.CSC_gb_35)
        self.CSLS1_D_LE.setMinimumSize(QtCore.QSize(50, 0))
        self.CSLS1_D_LE.setMaximumSize(QtCore.QSize(100, 16777215))
        self.CSLS1_D_LE.setObjectName("CSLS1_D_LE")
        self.verticalLayout_44.addWidget(self.CSLS1_D_LE)
        self.horizontalLayout_46.addLayout(self.verticalLayout_44)
        self.gridLayout_31.addLayout(self.horizontalLayout_46, 0, 0, 1, 1)
        self.verticalLayout_22.addWidget(self.CSC_gb_35)
        self.horizontalLayout_9.addWidget(self.frame_38)
        self.frame_39 = QtWidgets.QFrame(self.frame_26)
        self.frame_39.setMinimumSize(QtCore.QSize(380, 0))
        self.frame_39.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_39.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_39.setObjectName("frame_39")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.frame_39)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.CSC_gb_36 = QtWidgets.QGroupBox(self.frame_39)
        self.CSC_gb_36.setMinimumSize(QtCore.QSize(350, 0))
        font = QtGui.QFont()
        font.setItalic(False)
        font.setUnderline(False)
        self.CSC_gb_36.setFont(font)
        self.CSC_gb_36.setAutoFillBackground(True)
        self.CSC_gb_36.setFlat(False)
        self.CSC_gb_36.setCheckable(False)
        self.CSC_gb_36.setObjectName("CSC_gb_36")
        self.gridLayout_33 = QtWidgets.QGridLayout(self.CSC_gb_36)
        self.gridLayout_33.setObjectName("gridLayout_33")
        self.horizontalLayout_58 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_58.setObjectName("horizontalLayout_58")
        self.verticalLayout_53 = QtWidgets.QVBoxLayout()
        self.verticalLayout_53.setObjectName("verticalLayout_53")
        self.label_83 = QtWidgets.QLabel(self.CSC_gb_36)
        self.label_83.setObjectName("label_83")
        self.verticalLayout_53.addWidget(self.label_83)
        self.CSLS2_V_LE = QtWidgets.QLineEdit(self.CSC_gb_36)
        self.CSLS2_V_LE.setMinimumSize(QtCore.QSize(210, 0))
        self.CSLS2_V_LE.setMaximumSize(QtCore.QSize(350, 16777215))
        self.CSLS2_V_LE.setObjectName("CSLS2_V_LE")
        self.verticalLayout_53.addWidget(self.CSLS2_V_LE)
        self.horizontalLayout_58.addLayout(self.verticalLayout_53)
        self.verticalLayout_54 = QtWidgets.QVBoxLayout()
        self.verticalLayout_54.setObjectName("verticalLayout_54")
        self.label_94 = QtWidgets.QLabel(self.CSC_gb_36)
        self.label_94.setObjectName("label_94")
        self.verticalLayout_54.addWidget(self.label_94)
        self.CSLS2_D_LE = QtWidgets.QLineEdit(self.CSC_gb_36)
        self.CSLS2_D_LE.setMinimumSize(QtCore.QSize(50, 0))
        self.CSLS2_D_LE.setMaximumSize(QtCore.QSize(100, 16777215))
        self.CSLS2_D_LE.setObjectName("CSLS2_D_LE")
        self.verticalLayout_54.addWidget(self.CSLS2_D_LE)
        self.horizontalLayout_58.addLayout(self.verticalLayout_54)
        self.gridLayout_33.addLayout(self.horizontalLayout_58, 0, 0, 1, 1)
        self.verticalLayout_23.addWidget(self.CSC_gb_36)
        self.horizontalLayout_9.addWidget(self.frame_39)
        self.frame_40 = QtWidgets.QFrame(self.frame_26)
        self.frame_40.setMinimumSize(QtCore.QSize(380, 0))
        self.frame_40.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_40.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_40.setObjectName("frame_40")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.frame_40)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.CSC_gb_37 = QtWidgets.QGroupBox(self.frame_40)
        self.CSC_gb_37.setMinimumSize(QtCore.QSize(350, 0))
        font = QtGui.QFont()
        font.setItalic(False)
        font.setUnderline(False)
        self.CSC_gb_37.setFont(font)
        self.CSC_gb_37.setAutoFillBackground(True)
        self.CSC_gb_37.setFlat(False)
        self.CSC_gb_37.setCheckable(False)
        self.CSC_gb_37.setObjectName("CSC_gb_37")
        self.gridLayout_51 = QtWidgets.QGridLayout(self.CSC_gb_37)
        self.gridLayout_51.setObjectName("gridLayout_51")
        self.horizontalLayout_75 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_75.setObjectName("horizontalLayout_75")
        self.verticalLayout_75 = QtWidgets.QVBoxLayout()
        self.verticalLayout_75.setObjectName("verticalLayout_75")
        self.label_115 = QtWidgets.QLabel(self.CSC_gb_37)
        self.label_115.setObjectName("label_115")
        self.verticalLayout_75.addWidget(self.label_115)
        self.DVLS_V_LE = QtWidgets.QLineEdit(self.CSC_gb_37)
        self.DVLS_V_LE.setMinimumSize(QtCore.QSize(210, 0))
        self.DVLS_V_LE.setMaximumSize(QtCore.QSize(350, 16777215))
        self.DVLS_V_LE.setObjectName("DVLS_V_LE")
        self.verticalLayout_75.addWidget(self.DVLS_V_LE)
        self.horizontalLayout_75.addLayout(self.verticalLayout_75)
        self.verticalLayout_76 = QtWidgets.QVBoxLayout()
        self.verticalLayout_76.setObjectName("verticalLayout_76")
        self.label_116 = QtWidgets.QLabel(self.CSC_gb_37)
        self.label_116.setObjectName("label_116")
        self.verticalLayout_76.addWidget(self.label_116)
        self.DVLS_D_LE = QtWidgets.QLineEdit(self.CSC_gb_37)
        self.DVLS_D_LE.setMinimumSize(QtCore.QSize(50, 0))
        self.DVLS_D_LE.setMaximumSize(QtCore.QSize(100, 16777215))
        self.DVLS_D_LE.setObjectName("DVLS_D_LE")
        self.verticalLayout_76.addWidget(self.DVLS_D_LE)
        self.horizontalLayout_75.addLayout(self.verticalLayout_76)
        self.gridLayout_51.addLayout(self.horizontalLayout_75, 0, 0, 1, 1)
        self.verticalLayout_24.addWidget(self.CSC_gb_37)
        self.horizontalLayout_9.addWidget(self.frame_40)
        self.gridLayout_2.addLayout(self.horizontalLayout_9, 1, 0, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.frame_41 = QtWidgets.QFrame(self.frame_26)
        self.frame_41.setMinimumSize(QtCore.QSize(380, 0))
        self.frame_41.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_41.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_41.setObjectName("frame_41")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.frame_41)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.CSC_gb_38 = QtWidgets.QGroupBox(self.frame_41)
        self.CSC_gb_38.setMinimumSize(QtCore.QSize(350, 0))
        font = QtGui.QFont()
        font.setItalic(False)
        font.setUnderline(False)
        self.CSC_gb_38.setFont(font)
        self.CSC_gb_38.setAutoFillBackground(True)
        self.CSC_gb_38.setFlat(False)
        self.CSC_gb_38.setCheckable(False)
        self.CSC_gb_38.setObjectName("CSC_gb_38")
        self.gridLayout_35 = QtWidgets.QGridLayout(self.CSC_gb_38)
        self.gridLayout_35.setObjectName("gridLayout_35")
        self.horizontalLayout_76 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_76.setObjectName("horizontalLayout_76")
        self.verticalLayout_79 = QtWidgets.QVBoxLayout()
        self.verticalLayout_79.setObjectName("verticalLayout_79")
        self.label_117 = QtWidgets.QLabel(self.CSC_gb_38)
        self.label_117.setObjectName("label_117")
        self.verticalLayout_79.addWidget(self.label_117)
        self.CSVP_V_LE = QtWidgets.QLineEdit(self.CSC_gb_38)
        self.CSVP_V_LE.setMinimumSize(QtCore.QSize(210, 0))
        self.CSVP_V_LE.setMaximumSize(QtCore.QSize(350, 16777215))
        self.CSVP_V_LE.setObjectName("CSVP_V_LE")
        self.verticalLayout_79.addWidget(self.CSVP_V_LE)
        self.horizontalLayout_76.addLayout(self.verticalLayout_79)
        self.verticalLayout_80 = QtWidgets.QVBoxLayout()
        self.verticalLayout_80.setObjectName("verticalLayout_80")
        self.label_118 = QtWidgets.QLabel(self.CSC_gb_38)
        self.label_118.setObjectName("label_118")
        self.verticalLayout_80.addWidget(self.label_118)
        self.CSVP_D_LE = QtWidgets.QLineEdit(self.CSC_gb_38)
        self.CSVP_D_LE.setMinimumSize(QtCore.QSize(50, 0))
        self.CSVP_D_LE.setMaximumSize(QtCore.QSize(100, 16777215))
        self.CSVP_D_LE.setObjectName("CSVP_D_LE")
        self.verticalLayout_80.addWidget(self.CSVP_D_LE)
        self.horizontalLayout_76.addLayout(self.verticalLayout_80)
        self.gridLayout_35.addLayout(self.horizontalLayout_76, 0, 0, 1, 1)
        self.verticalLayout_25.addWidget(self.CSC_gb_38)
        self.horizontalLayout_10.addWidget(self.frame_41)
        self.frame_42 = QtWidgets.QFrame(self.frame_26)
        self.frame_42.setMinimumSize(QtCore.QSize(380, 0))
        self.frame_42.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_42.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_42.setObjectName("frame_42")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.frame_42)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.CSC_gb_39 = QtWidgets.QGroupBox(self.frame_42)
        self.CSC_gb_39.setMinimumSize(QtCore.QSize(350, 0))
        font = QtGui.QFont()
        font.setItalic(False)
        font.setUnderline(False)
        self.CSC_gb_39.setFont(font)
        self.CSC_gb_39.setAutoFillBackground(True)
        self.CSC_gb_39.setFlat(False)
        self.CSC_gb_39.setCheckable(False)
        self.CSC_gb_39.setObjectName("CSC_gb_39")
        self.gridLayout_45 = QtWidgets.QGridLayout(self.CSC_gb_39)
        self.gridLayout_45.setObjectName("gridLayout_45")
        self.horizontalLayout_78 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_78.setObjectName("horizontalLayout_78")
        self.verticalLayout_81 = QtWidgets.QVBoxLayout()
        self.verticalLayout_81.setObjectName("verticalLayout_81")
        self.label_120 = QtWidgets.QLabel(self.CSC_gb_39)
        self.label_120.setObjectName("label_120")
        self.verticalLayout_81.addWidget(self.label_120)
        self.CSIL_V_LE = QtWidgets.QLineEdit(self.CSC_gb_39)
        self.CSIL_V_LE.setMinimumSize(QtCore.QSize(210, 0))
        self.CSIL_V_LE.setMaximumSize(QtCore.QSize(350, 16777215))
        self.CSIL_V_LE.setObjectName("CSIL_V_LE")
        self.verticalLayout_81.addWidget(self.CSIL_V_LE)
        self.horizontalLayout_78.addLayout(self.verticalLayout_81)
        self.verticalLayout_82 = QtWidgets.QVBoxLayout()
        self.verticalLayout_82.setObjectName("verticalLayout_82")
        self.label_121 = QtWidgets.QLabel(self.CSC_gb_39)
        self.label_121.setObjectName("label_121")
        self.verticalLayout_82.addWidget(self.label_121)
        self.CSIL_D_LE = QtWidgets.QLineEdit(self.CSC_gb_39)
        self.CSIL_D_LE.setMinimumSize(QtCore.QSize(50, 0))
        self.CSIL_D_LE.setMaximumSize(QtCore.QSize(100, 16777215))
        self.CSIL_D_LE.setObjectName("CSIL_D_LE")
        self.verticalLayout_82.addWidget(self.CSIL_D_LE)
        self.horizontalLayout_78.addLayout(self.verticalLayout_82)
        self.gridLayout_45.addLayout(self.horizontalLayout_78, 0, 0, 1, 1)
        self.verticalLayout_26.addWidget(self.CSC_gb_39)
        self.horizontalLayout_10.addWidget(self.frame_42)
        self.frame_43 = QtWidgets.QFrame(self.frame_26)
        self.frame_43.setMinimumSize(QtCore.QSize(380, 0))
        self.frame_43.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_43.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_43.setObjectName("frame_43")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout(self.frame_43)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.CSC_gb_40 = QtWidgets.QGroupBox(self.frame_43)
        self.CSC_gb_40.setMinimumSize(QtCore.QSize(350, 0))
        font = QtGui.QFont()
        font.setItalic(False)
        font.setUnderline(False)
        self.CSC_gb_40.setFont(font)
        self.CSC_gb_40.setAutoFillBackground(True)
        self.CSC_gb_40.setFlat(False)
        self.CSC_gb_40.setCheckable(False)
        self.CSC_gb_40.setObjectName("CSC_gb_40")
        self.gridLayout_54 = QtWidgets.QGridLayout(self.CSC_gb_40)
        self.gridLayout_54.setObjectName("gridLayout_54")
        self.horizontalLayout_80 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_80.setObjectName("horizontalLayout_80")
        self.verticalLayout_83 = QtWidgets.QVBoxLayout()
        self.verticalLayout_83.setObjectName("verticalLayout_83")
        self.label_123 = QtWidgets.QLabel(self.CSC_gb_40)
        self.label_123.setObjectName("label_123")
        self.verticalLayout_83.addWidget(self.label_123)
        self.DVVDR_V_LE = QtWidgets.QLineEdit(self.CSC_gb_40)
        self.DVVDR_V_LE.setMinimumSize(QtCore.QSize(210, 0))
        self.DVVDR_V_LE.setMaximumSize(QtCore.QSize(350, 16777215))
        self.DVVDR_V_LE.setObjectName("DVVDR_V_LE")
        self.verticalLayout_83.addWidget(self.DVVDR_V_LE)
        self.horizontalLayout_80.addLayout(self.verticalLayout_83)
        self.verticalLayout_84 = QtWidgets.QVBoxLayout()
        self.verticalLayout_84.setObjectName("verticalLayout_84")
        self.label_124 = QtWidgets.QLabel(self.CSC_gb_40)
        self.label_124.setObjectName("label_124")
        self.verticalLayout_84.addWidget(self.label_124)
        self.DVVDR_D_LE = QtWidgets.QLineEdit(self.CSC_gb_40)
        self.DVVDR_D_LE.setMinimumSize(QtCore.QSize(50, 0))
        self.DVVDR_D_LE.setMaximumSize(QtCore.QSize(100, 16777215))
        self.DVVDR_D_LE.setObjectName("DVVDR_D_LE")
        self.verticalLayout_84.addWidget(self.DVVDR_D_LE)
        self.horizontalLayout_80.addLayout(self.verticalLayout_84)
        self.gridLayout_54.addLayout(self.horizontalLayout_80, 0, 0, 1, 1)
        self.verticalLayout_27.addWidget(self.CSC_gb_40)
        self.horizontalLayout_10.addWidget(self.frame_43)
        self.gridLayout_2.addLayout(self.horizontalLayout_10, 2, 0, 1, 1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.frame_44 = QtWidgets.QFrame(self.frame_26)
        self.frame_44.setMinimumSize(QtCore.QSize(380, 0))
        self.frame_44.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_44.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_44.setObjectName("frame_44")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout(self.frame_44)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.CSC_gb_41 = QtWidgets.QGroupBox(self.frame_44)
        self.CSC_gb_41.setMinimumSize(QtCore.QSize(350, 0))
        font = QtGui.QFont()
        font.setItalic(False)
        font.setUnderline(False)
        self.CSC_gb_41.setFont(font)
        self.CSC_gb_41.setAutoFillBackground(True)
        self.CSC_gb_41.setFlat(False)
        self.CSC_gb_41.setCheckable(False)
        self.CSC_gb_41.setObjectName("CSC_gb_41")
        self.gridLayout_48 = QtWidgets.QGridLayout(self.CSC_gb_41)
        self.gridLayout_48.setObjectName("gridLayout_48")
        self.horizontalLayout_82 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_82.setObjectName("horizontalLayout_82")
        self.verticalLayout_85 = QtWidgets.QVBoxLayout()
        self.verticalLayout_85.setObjectName("verticalLayout_85")
        self.label_126 = QtWidgets.QLabel(self.CSC_gb_41)
        self.label_126.setObjectName("label_126")
        self.verticalLayout_85.addWidget(self.label_126)
        self.CSIE1_V_LE = QtWidgets.QLineEdit(self.CSC_gb_41)
        self.CSIE1_V_LE.setMinimumSize(QtCore.QSize(210, 0))
        self.CSIE1_V_LE.setMaximumSize(QtCore.QSize(350, 16777215))
        self.CSIE1_V_LE.setObjectName("CSIE1_V_LE")
        self.verticalLayout_85.addWidget(self.CSIE1_V_LE)
        self.horizontalLayout_82.addLayout(self.verticalLayout_85)
        self.verticalLayout_86 = QtWidgets.QVBoxLayout()
        self.verticalLayout_86.setObjectName("verticalLayout_86")
        self.label_127 = QtWidgets.QLabel(self.CSC_gb_41)
        self.label_127.setObjectName("label_127")
        self.verticalLayout_86.addWidget(self.label_127)
        self.CSIE1_D_LE = QtWidgets.QLineEdit(self.CSC_gb_41)
        self.CSIE1_D_LE.setMinimumSize(QtCore.QSize(50, 0))
        self.CSIE1_D_LE.setMaximumSize(QtCore.QSize(100, 16777215))
        self.CSIE1_D_LE.setObjectName("CSIE1_D_LE")
        self.verticalLayout_86.addWidget(self.CSIE1_D_LE)
        self.horizontalLayout_82.addLayout(self.verticalLayout_86)
        self.gridLayout_48.addLayout(self.horizontalLayout_82, 0, 0, 1, 1)
        self.verticalLayout_28.addWidget(self.CSC_gb_41)
        self.horizontalLayout_11.addWidget(self.frame_44)
        self.frame_45 = QtWidgets.QFrame(self.frame_26)
        self.frame_45.setMinimumSize(QtCore.QSize(380, 0))
        self.frame_45.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_45.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_45.setObjectName("frame_45")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout(self.frame_45)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.CSC_gb_42 = QtWidgets.QGroupBox(self.frame_45)
        self.CSC_gb_42.setMinimumSize(QtCore.QSize(350, 0))
        font = QtGui.QFont()
        font.setItalic(False)
        font.setUnderline(False)
        self.CSC_gb_42.setFont(font)
        self.CSC_gb_42.setAutoFillBackground(True)
        self.CSC_gb_42.setFlat(False)
        self.CSC_gb_42.setCheckable(False)
        self.CSC_gb_42.setObjectName("CSC_gb_42")
        self.gridLayout_59 = QtWidgets.QGridLayout(self.CSC_gb_42)
        self.gridLayout_59.setObjectName("gridLayout_59")
        self.horizontalLayout_84 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_84.setObjectName("horizontalLayout_84")
        self.verticalLayout_87 = QtWidgets.QVBoxLayout()
        self.verticalLayout_87.setObjectName("verticalLayout_87")
        self.label_129 = QtWidgets.QLabel(self.CSC_gb_42)
        self.label_129.setObjectName("label_129")
        self.verticalLayout_87.addWidget(self.label_129)
        self.CSIE2_V_LE = QtWidgets.QLineEdit(self.CSC_gb_42)
        self.CSIE2_V_LE.setMinimumSize(QtCore.QSize(210, 0))
        self.CSIE2_V_LE.setMaximumSize(QtCore.QSize(350, 16777215))
        self.CSIE2_V_LE.setObjectName("CSIE2_V_LE")
        self.verticalLayout_87.addWidget(self.CSIE2_V_LE)
        self.horizontalLayout_84.addLayout(self.verticalLayout_87)
        self.verticalLayout_88 = QtWidgets.QVBoxLayout()
        self.verticalLayout_88.setObjectName("verticalLayout_88")
        self.label_130 = QtWidgets.QLabel(self.CSC_gb_42)
        self.label_130.setObjectName("label_130")
        self.verticalLayout_88.addWidget(self.label_130)
        self.CSIE2_D_LE = QtWidgets.QLineEdit(self.CSC_gb_42)
        self.CSIE2_D_LE.setMinimumSize(QtCore.QSize(50, 0))
        self.CSIE2_D_LE.setMaximumSize(QtCore.QSize(100, 16777215))
        self.CSIE2_D_LE.setObjectName("CSIE2_D_LE")
        self.verticalLayout_88.addWidget(self.CSIE2_D_LE)
        self.horizontalLayout_84.addLayout(self.verticalLayout_88)
        self.gridLayout_59.addLayout(self.horizontalLayout_84, 0, 0, 1, 1)
        self.verticalLayout_29.addWidget(self.CSC_gb_42)
        self.horizontalLayout_11.addWidget(self.frame_45)
        self.frame_46 = QtWidgets.QFrame(self.frame_26)
        self.frame_46.setMinimumSize(QtCore.QSize(380, 0))
        self.frame_46.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_46.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_46.setObjectName("frame_46")
        self.gridLayout_60 = QtWidgets.QGridLayout(self.frame_46)
        self.gridLayout_60.setObjectName("gridLayout_60")
        self.CSC_gb_43 = QtWidgets.QGroupBox(self.frame_46)
        self.CSC_gb_43.setMinimumSize(QtCore.QSize(350, 0))
        font = QtGui.QFont()
        font.setItalic(False)
        font.setUnderline(False)
        self.CSC_gb_43.setFont(font)
        self.CSC_gb_43.setAutoFillBackground(True)
        self.CSC_gb_43.setFlat(False)
        self.CSC_gb_43.setCheckable(False)
        self.CSC_gb_43.setObjectName("CSC_gb_43")
        self.gridLayout_61 = QtWidgets.QGridLayout(self.CSC_gb_43)
        self.gridLayout_61.setObjectName("gridLayout_61")
        self.horizontalLayout_86 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_86.setObjectName("horizontalLayout_86")
        self.verticalLayout_89 = QtWidgets.QVBoxLayout()
        self.verticalLayout_89.setObjectName("verticalLayout_89")
        self.label_132 = QtWidgets.QLabel(self.CSC_gb_43)
        self.label_132.setObjectName("label_132")
        self.verticalLayout_89.addWidget(self.label_132)
        self.DVLR_V_LE = QtWidgets.QLineEdit(self.CSC_gb_43)
        self.DVLR_V_LE.setMinimumSize(QtCore.QSize(210, 0))
        self.DVLR_V_LE.setMaximumSize(QtCore.QSize(350, 16777215))
        self.DVLR_V_LE.setObjectName("DVLR_V_LE")
        self.verticalLayout_89.addWidget(self.DVLR_V_LE)
        self.horizontalLayout_86.addLayout(self.verticalLayout_89)
        self.verticalLayout_90 = QtWidgets.QVBoxLayout()
        self.verticalLayout_90.setObjectName("verticalLayout_90")
        self.label_133 = QtWidgets.QLabel(self.CSC_gb_43)
        self.label_133.setObjectName("label_133")
        self.verticalLayout_90.addWidget(self.label_133)
        self.lineEdit_126 = QtWidgets.QLineEdit(self.CSC_gb_43)
        self.lineEdit_126.setMinimumSize(QtCore.QSize(50, 0))
        self.lineEdit_126.setMaximumSize(QtCore.QSize(100, 16777215))
        self.lineEdit_126.setObjectName("lineEdit_126")
        self.verticalLayout_90.addWidget(self.lineEdit_126)
        self.horizontalLayout_86.addLayout(self.verticalLayout_90)
        self.gridLayout_61.addLayout(self.horizontalLayout_86, 0, 0, 1, 1)
        self.gridLayout_60.addWidget(self.CSC_gb_43, 0, 0, 1, 1)
        self.horizontalLayout_11.addWidget(self.frame_46)
        self.gridLayout_2.addLayout(self.horizontalLayout_11, 4, 0, 1, 1)
        self.gridLayout_5.addWidget(self.frame_26, 0, 0, 1, 1)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_4)
        self.gridLayout_4.addWidget(self.scrollArea_3, 0, 0, 1, 1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_3)
        self.tabWidget.addTab(self.tab_2, "")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 20, 1271, 641))
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame.raise_()
        self.tabWidget.raise_()
        OPWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(OPWindow)
        self.statusbar.setObjectName("statusbar")
        OPWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(OPWindow)
        self.actionExit.setVisible(True)
        self.actionExit.setMenuRole(QtWidgets.QAction.TextHeuristicRole)
        self.actionExit.setShortcutVisibleInContextMenu(True)
        self.actionExit.setObjectName("actionExit")

        self.retranslateUi(OPWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(OPWindow)

    def retranslateUi(self, OPWindow):
        _translate = QtCore.QCoreApplication.translate
        OPWindow.setWindowTitle(_translate("OPWindow", "MainWindow"))
        self.CSC_gb_18.setTitle(_translate("OPWindow", "TID"))
        self.label_75.setText(_translate("OPWindow", "Health Status"))
        self.CSC_gb_19.setTitle(_translate("OPWindow", "VoIP Phone"))
        self.label_78.setText(_translate("OPWindow", "Health Status"))
        self.CSC_gb_25.setTitle(_translate("OPWindow", "DV VoIP Phone"))
        self.label_100.setText(_translate("OPWindow", "Health Status"))
        self.CSC_gb_12.setTitle(_translate("OPWindow", "CS Computer"))
        self.label_47.setText(_translate("OPWindow", "Health Status"))
        self.CSC_gb_13.setTitle(_translate("OPWindow", "Video Encoder"))
        self.label_52.setText(_translate("OPWindow", "Health Status"))
        self.CSC_gb_22.setTitle(_translate("OPWindow", "DV Computer"))
        self.label_87.setText(_translate("OPWindow", "Health Status"))
        self.CSC_gb_20.setTitle(_translate("OPWindow", "IP Encryptor-1"))
        self.label_81.setText(_translate("OPWindow", "Health Status"))
        self.CSC_gb_21.setTitle(_translate("OPWindow", "IP Encryptor-2"))
        self.label_84.setText(_translate("OPWindow", "Health Status"))
        self.CSC_gb_27.setTitle(_translate("OPWindow", "DV LoS Radio"))
        self.label_109.setText(_translate("OPWindow", "Health Status"))
        self.CSC_gb_28.setTitle(_translate("OPWindow", "LOS Radio"))
        self.label_96.setText(_translate("OPWindow", "Health Status"))
        self.CSC_gb_14.setTitle(_translate("OPWindow", "CS LAN Switch-1"))
        self.label_53.setText(_translate("OPWindow", "Health Status"))
        self.label_54.setText(_translate("OPWindow", "FO Port Status"))
        self.label_55.setText(_translate("OPWindow", "     Port1"))
        self.label_56.setText(_translate("OPWindow", "     Port2"))
        self.label_57.setText(_translate("OPWindow", "     Port3"))
        self.CSC_gb_15.setTitle(_translate("OPWindow", "CS LAN Switch-2"))
        self.label_60.setText(_translate("OPWindow", "Health Status"))
        self.label_61.setText(_translate("OPWindow", "FO Port Status"))
        self.label_62.setText(_translate("OPWindow", "    Port1"))
        self.label_63.setText(_translate("OPWindow", "    Port2"))
        self.label_64.setText(_translate("OPWindow", "    Port3"))
        self.CSC_gb_23.setTitle(_translate("OPWindow", "DV LAN Switch"))
        self.label_88.setText(_translate("OPWindow", "Health Status"))
        self.label_89.setText(_translate("OPWindow", "FO Port Status"))
        self.label_90.setText(_translate("OPWindow", "    Port1"))
        self.label_91.setText(_translate("OPWindow", "    Port2"))
        self.label_92.setText(_translate("OPWindow", "    Port3"))
        self.CSC_gb_16.setTitle(_translate("OPWindow", "VoIP Gateway"))
        self.label_69.setText(_translate("OPWindow", "Health Status"))
        self.CSC_gb_17.setTitle(_translate("OPWindow", "mini IP Logger"))
        self.label_72.setText(_translate("OPWindow", "Health Status"))
        self.CSC_gb_24.setTitle(_translate("OPWindow", "DV Video Decoder & Recorder"))
        self.label_97.setText(_translate("OPWindow", "Health Status"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("OPWindow", "LRU HEALTH MSG"))
        self.CSC_gb_26.setTitle(_translate("OPWindow", "LoS Radio"))
        self.label_104.setText(_translate("OPWindow", "Software Version"))
        self.label_105.setText(_translate("OPWindow", " Release Date"))
        self.CSC_gb_29.setTitle(_translate("OPWindow", "TID"))
        self.label_73.setText(_translate("OPWindow", "Software Version"))
        self.label_74.setText(_translate("OPWindow", " Release Date"))
        self.CSC_gb_30.setTitle(_translate("OPWindow", "VoIP Phone"))
        self.label_77.setText(_translate("OPWindow", "Software Version"))
        self.label_79.setText(_translate("OPWindow", " Release Date"))
        self.CSC_gb_31.setTitle(_translate("OPWindow", "DV VoIP Phone"))
        self.label_98.setText(_translate("OPWindow", "Software Version"))
        self.label_99.setText(_translate("OPWindow", " Release Date"))
        self.CSC_gb_32.setTitle(_translate("OPWindow", "CS Computer"))
        self.label_49.setText(_translate("OPWindow", "Software Version"))
        self.label_50.setText(_translate("OPWindow", " Release Date"))
        self.CSC_gb_33.setTitle(_translate("OPWindow", "Video Encoder"))
        self.label_51.setText(_translate("OPWindow", "Software Version"))
        self.label_58.setText(_translate("OPWindow", " Release Date"))
        self.CSC_gb_34.setTitle(_translate("OPWindow", "DV Computer"))
        self.label_85.setText(_translate("OPWindow", "Software Version"))
        self.label_86.setText(_translate("OPWindow", " Release Date"))
        self.CSC_gb_35.setTitle(_translate("OPWindow", "CS LAN Switch-1"))
        self.label_66.setText(_translate("OPWindow", "Software Version"))
        self.label_67.setText(_translate("OPWindow", " Release Date"))
        self.CSC_gb_36.setTitle(_translate("OPWindow", "CS LAN Switch-2"))
        self.label_83.setText(_translate("OPWindow", "Software Version"))
        self.label_94.setText(_translate("OPWindow", " Release Date"))
        self.CSC_gb_37.setTitle(_translate("OPWindow", "DV LAN Switch"))
        self.label_115.setText(_translate("OPWindow", "Software Version"))
        self.label_116.setText(_translate("OPWindow", " Release Date"))
        self.CSC_gb_38.setTitle(_translate("OPWindow", "VoIP Gateway"))
        self.label_117.setText(_translate("OPWindow", "Software Version"))
        self.label_118.setText(_translate("OPWindow", " Release Date"))
        self.CSC_gb_39.setTitle(_translate("OPWindow", "mini IP Logger"))
        self.label_120.setText(_translate("OPWindow", "Software Version"))
        self.label_121.setText(_translate("OPWindow", " Release Date"))
        self.CSC_gb_40.setTitle(_translate("OPWindow", "DV Video Decoder & Recorder"))
        self.label_123.setText(_translate("OPWindow", "Software Version"))
        self.label_124.setText(_translate("OPWindow", " Release Date"))
        self.CSC_gb_41.setTitle(_translate("OPWindow", "IP Encryptor-1"))
        self.label_126.setText(_translate("OPWindow", "Software Version"))
        self.label_127.setText(_translate("OPWindow", " Release Date"))
        self.CSC_gb_42.setTitle(_translate("OPWindow", "IP Encryptor-2"))
        self.label_129.setText(_translate("OPWindow", "Software Version"))
        self.label_130.setText(_translate("OPWindow", " Release Date"))
        self.CSC_gb_43.setTitle(_translate("OPWindow", "LoS Radio"))
        self.label_132.setText(_translate("OPWindow", "Software Version"))
        self.label_133.setText(_translate("OPWindow", " Release Date"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("OPWindow", "LRU SW VER"))
        self.actionExit.setText(_translate("OPWindow", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    OPWindow = QtWidgets.QMainWindow()
    ui = Ui_OPWindow()
    ui.setupUi(OPWindow)
    OPWindow.show()
    sys.exit(app.exec_())
